### ISSUE TITLE
add VERSION property in main Stimulus object

### ISSUE THREAD

**Issue by bdavidxyz** [stimulusjs/stimulus#100]
lodash has a property VERSION in the global object; jquery equivalent is $.fn.jquery. It would be very handy to have Stimulus.VERSION that output the current version number.

**Comment by javan** [comment]
In your case, what would it be handy for?

**Comment by bdavidxyz** [comment]
In debug mode, to check that 1) Stimulus is loaded 2) with the correct version, in test mode, that the Stimulus version loaded in my test environment is the correct one.

**Comment by javan** [comment]
Thanks! We will consider it.
