### ISSUE TITLE
How does this Gel with Progressive Web Apps (PWA)

### ISSUE THREAD

**Issue by RehanSaeed** [stimulusjs/stimulus#103]
I'm trying to get my head around Stimulus and how it could work with service workers and PWA's with the aim of making your app somewhat work offline or even totally offline if the app lends itself to that direction.

You'd be able to cache your JavaScript, CSS, fonts, images etc. but what about HTML? Is it possible to create an app shell i.e. a shared html container with some basic CSS inlined in the `head` tag, so that users get something to see instantly and then content being switched in the `body` tag.

**Comment by RehanSaeed** [comment]
I'd just like to add a related and interesting [blog post](https://jakearchibald.com/2016/streams-ftw/) by Jake Archibald, talking about the web streams API and service workers producing very fast sites.

**Comment by javan** [comment]
Great topic! If you want to continue the discussion, please post this on the [Stimulus Discourse](https://discourse.stimulusjs.org/) community forum.
