### ISSUE TITLE
Support for kebab case target names

### ISSUE THREAD

**Issue by saneef** [stimulusjs/stimulus#106]
The controller names supports kebab case, since they only used to connect with filenames.  But the same approach of kebab case don't work well with `static targets`.

Or, is it advised to stick with camelCase for all names in Stimulus?

```html
<div class="media-uploader" data-controller="media-uploader">
  <div class="media-uploader__drop-area" data-target="media-uploader.drop-area"></div>
</div>
```

```js
export default class extends Controller {
  static targets = ['drop-area'];
  
  connect() {
   //  Excepts to work this.dropAreaTarget
  }
}
```

**Comment by javan** [comment]
Target names map directly to property names so it's best to stick with camelCase. See https://github.com/stimulusjs/stimulus/issues/70#issuecomment-359991756 for a rundown of the capitalization conventions.
