### ISSUE TITLE
Plans to host it on a cdn ?

### ISSUE THREAD

**Issue by happysalada** [stimulusjs/stimulus#108]
Just curious if there are plans to host it on a cdn ?
(I don't know if it costs money for open source project, or if the application process is long and painful)

**Comment by mdesantis** [comment]
You can use [unpkg](https://unpkg.com): https://unpkg.com/stimulus@1.0.1/

**Comment by xhafan** [comment]
Alternative CDN: https://www.jsdelivr.com/package/npm/stimulus
