### ISSUE TITLE
When target is not present, static target throws an error whereas target.find don't

### ISSUE THREAD

**Issue by adrienpoly** [stimulusjs/stimulus#111]
Usure if it is an issue or a suggestion of improvements

I love using the static target definition and then call `this.mytargetTarget.doSomething`. 

They are cases where the target are not always visible in the DOM.

Initially I had a function like this

```js
if (this.targets.find("foo")) {
    console.log("if there is a foo target then do something with it");
}
```

This is working fine but wanted to fully update my code to use Stimulus static targets

```js
  static targets = ["foo"]
  
  ...
  if (this.fooTarget) {
    console.log("if there is a foo target then do something with it");
  }
  ...
```
but with this last code I get the following error when the `foo`target is not available in the DOM

```error
Error connecting controller

Error: Missing target element "myController.foo"
```
I thought it would be nice to get a `false` return from `this.fooTarget` so that we could use it to test presence or not of elements in the same way it is working with `this.targets.find("foo")`

**Comment by sstephenson** [comment]
This is by design. You can use `this.hasFooTarget` to see whether there’s a `foo` target in scope. See [the Handbook](https://stimulusjs.org/handbook/building-something-real#whats-with-that-static-targets-line) for more details.

**Comment by adrienpoly** [comment]
Thanks, I clearly overlooked this method, sorry about that

**Comment by sstephenson** [comment]
No problem!
