### ISSUE TITLE
Error parsing descriptor string in markup inserted by third party plugins

### ISSUE THREAD

**Issue by beghelli** [stimulusjs/stimulus#114]
Hello, and thanks for this work, it's really awesome.

In my application I am using a jQuery plugin that is already using "data-action" in its markup, for a completely different purpose. I've built an stimulus controller that encapsulates the initialization of this plugin and some other custom implementations.

When the plugin is initialized, it adds some HTML markup with the "data-action" and stimulus tries to read it, throwing the parsing errors.

It would be helpful if we could tell stimulus to ignore parts of the controller element markup, avoiding the parsing errors. Not sure if that's possible, but I couldn't find anything like that. 

Thanks again.

**Comment by kmmbvnr** [comment]
It looks there is possibility to instantiate a stimulus application class with custom schema for data-attr attribute naming 

https://github.com/stimulusjs/stimulus/blob/master/packages/%40stimulus/core/src/schema.ts

**Comment by beghelli** [comment]
thanks @kmmbvnr 

I think it makes much more sense to use a custom schema than to keep worrying about all third party libraries you might want to use. Good catch.
