### ISSUE TITLE
Consider adding a section for Lifecycle Callbacks in the handbook 

### ISSUE THREAD

**Issue by AWaselnuk** [stimulusjs/stimulus#117]
I found it really hard to figure out what lifecycle hooks were available in Stimulus until I read the Handbook cover to cover and found them buried in the section about 'Managing State'.

What do you think about pulling them out into a distinct section so they are easier to find?

Another option could be to publish some more concise docs that read less like a guide and simply outline the API that a `Controller` provides you.

Thanks for your consideration :)

**Comment by sstephenson** [comment]
Thanks for raising the issue. I agree that the table of lifecycle callbacks is difficult to find.

However, there’s only three callbacks to document. I don’t really think they merit their own chapter in the handbook.

We’re planning on adding full API documentation for the next release and I suspect lifecycle callback methods will be quite natural to explain in the `Controller` class. 

Closing for now, but please feel free to open more documentation issues as you encounter them.

**Comment by AWaselnuk** [comment]
> We’re planning on adding full API documentation for the next release and I suspect lifecycle callback methods will be quite natural to explain in the Controller class.

This would solve the problem perfectly. Thanks for letting me know!
