### ISSUE TITLE
Event capture via useCapture

### ISSUE THREAD

**Issue by hopsoft** [stimulusjs/stimulus#118]
Is there a way to wire up an action with event capture i.e. `useCapture`?

Something along these lines perhaps?

```html
<a href="#" data-controller="example" data-action="capture|click->example#work">Example</a>
```

Additional context:
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Parameters

**Comment by sstephenson** [comment]
Not currently, but that would definitely be a nice feature.

If you’re interested in exploring this, start by adding a `useCapture` property to [`ActionDescriptor`](https://github.com/stimulusjs/stimulus/blob/master/packages/%40stimulus/core/src/action_descriptor.ts) and updating the parser accordingly. Then update the `connect` and `disconnect` methods to read that property in [`EventListener`](https://github.com/stimulusjs/stimulus/blob/master/packages/%40stimulus/core/src/event_listener.ts).

**Comment by tlowrimore** [comment]
@sstephenson I see this enhancement was closed without a PR. After looking through the source, it appears this feature was never added.  I'd be more than happy to create a PR for this feature, unless you know of a better way to capture an event dispatched from a parent controller, in a child controller.
