### ISSUE TITLE
Lifecycle callbacks messed up?

### ISSUE THREAD

**Issue by olhor** [stimulusjs/stimulus#122]
Hi,
this framework looks very promising but imao it has a core functionality problem. The problem lies within the  controller lifecycle callbacks.
Let's take the slideshow example from the "Handbook" which we extended with the "adding slide" functionality. Assuming we have the following code:
```
// slideshow.html
<div data-controller="slideshow" data-slideshow-index="1">
  <template data-target="slideshow.slideTemplate">
    <div data-target="slideshow.slide" class="slide" data-controller="slide"></div>
  </template>

  <button data-action="slideshow#addSlide">Add</button>
  <button data-action="slideshow#previous">←</button>
  <button data-action="slideshow#next">→</button>

  <div data-target="slideshow.slides">
    <div data-target="slideshow.slide" class="slide" data-controller="slide">🐵</div>
    <div data-target="slideshow.slide" class="slide" data-controller="slide">🙈</div>
    <div data-target="slideshow.slide" class="slide" data-controller="slide">🙉</div>
    <div data-target="slideshow.slide" class="slide" data-controller="slide">🙊</div>
  </div>
</div>
```
```
// slideshow_controller.js
export default class extends Controller {
    static targets = [ "slide", "slideTemplate", "slides" ]

    // irrelevant code

    addSlide(){
      console.log("adding slide")
      this.slidesTarget.insertAdjacentHTML("beforeend", this.slideTemplate)
      console.log('slide added')
    }

    get slideTemplate(){
      return this.slideTemplateTarget.innerHTML
    }
}
```
```
// slide_controller.js
export default class extends Controller {
    static targets = []

    initialize() {
      console.log("slide initialized")
    }

    connect() {
        console.log("slide connected")
    }
}
```
The order gets messed up when adding new slide element to the DOM. According to documentation, we have: 

`initialize | once, when the controller is first instantiated`
`connect | anytime the controller is connected to the DOM`

so our console log should look like this:
1. `adding slide`
2. `slide initialized`
3. `slide connected`
4. `slide added`

instead it looks like this:

1. `adding slide`
2. `slide added`
3. `slide initialized`
4. `slide connected`

Why such behaviour? Without any `initialize()`, `connect()` callback functions/events this looks like race conditions.

**Comment by sstephenson** [comment]
Everything you’ve described here is correct and is the expected behavior. There’s no race condition, but I understand it might look that way if you aren’t familiar with the implementation.

Controllers are connected and disconnected asynchronously in response to DOM changes. That’s because under the hood Stimulus uses a DOM [`MutationObserver`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to watch for these changes. 

Hope that clarifies the situation!

**Comment by olhor** [comment]
Thank You for the answer. Is there any way to listen for the `connect` event in order to sync with the DOM change regarding `connect`? I found the `EventListener` class within source code but I do not know its usage.
