### ISSUE TITLE
Security story/compatibility with CSP

### ISSUE THREAD

**Issue by david-a-wheeler** [stimulusjs/stimulus#123]
I am interested in Stimulus, but the documentation doesn't seem to say anything about security. In particular, is stimulus compatible with a CSP setting that disables all embedded JavaScript? Can I be confident that in case my cross site scripting countermeasures fail, there is no way for an attacker to run arbitrary JavaScript? If an attacker manages to insert code into the HTML, how can I ensure that what they can do is limited if I use Stimulus? Will stimulus only call classes marked as controllers? Does it eval anything in the HTML? I wouldn't be surprised if there is a very good story about this, but I simply don't see any documentation about it.  So this may be just a request to document this.

Thanks!

**Comment by sstephenson** [comment]
These are excellent questions. Would you mind re-posting them over on our [community forum](https://discourse.stimulusjs.org)? I’d be happy to answer them there.

**Comment by david-a-wheeler** [comment]
Sure. Done.

**Comment by lb-** [comment]
For those finding this later - here is the relevant security discussion

https://discuss.hotwired.dev/t/security-csp-and-stimulus/171/4
