### ISSUE TITLE
QUESTION: How to customize `data-` attribute names?

### ISSUE THREAD

**Issue by artificis** [stimulusjs/stimulus#124]
When I try to use other third party JS library (datepicker), stimulus complains. The datepicker library was using `data-action` attribute internally for dynamically generated DOM elements and I was using `data-controller` for `body` tag myself. What is the proper way to customize stimulus' `data-` attribute names, in order to avoid this name conflict?

```
data-controller
data-action
data-target
...
```

I think I saw it somewhere before, but can't remember now, tried to search but no luck.

Please let me know and can we document it in the stimulusjs.org?

**Comment by sstephenson** [comment]
We don’t recommend changing the attribute names, but if you must, you can pass a [`Schema`](https://github.com/stimulusjs/stimulus/blob/9bb10c60b09cfd471286710acbb736e1a21bc449/packages/%40stimulus/core/src/schema.ts) as the second argument to the [`Application` constructor](https://github.com/stimulusjs/stimulus/blob/9bb10c60b09cfd471286710acbb736e1a21bc449/packages/%40stimulus/core/src/application.ts#L18):

```js
const application = new Application(document.documentElement, {
  controllerAttribute: "data-controller",
  actionAttribute: "data-action"
  targetAttribute: "data-target"
})
// ...
application.start()
```
