### ISSUE TITLE
How to structure Stimulus within Rails apps - Examples

### ISSUE THREAD

**Issue by drale2k** [stimulusjs/stimulus#126]
Hi,

this is not really an issue (although somewhat it is) but i am look for example projects which go beyond introductions using just 1 controller, to learn how to structure Stimulus properly within mid-sized Rails applications.

Can you provide information on this or point to such applications? (Maybe examples from Basecamp)

Thanks

**Comment by javan** [comment]
Our community forum is a great place for questions like this: https://discourse.stimulusjs.org/t/work-with-rails/43
