### ISSUE TITLE
Greeting example in demo doesn't react to Enter

### ISSUE THREAD

**Issue by merwok** [stimulusjs/stimulus#129]
Hello!  I was on the project homepage to see what this framework is and tried the «Greet» demo.
Pressing Enter has no effect; one must click on the button.  It would be great to have both input methods.
Thanks for considering this!

**Comment by javan** [comment]
That would be nice, but we'd like to keep the example code short and sweet for now. Thanks for the suggestion!

**Comment by merwok** [comment]
Ok, too bad.  I had hoped that with a modern lib there could be short and sweet code to react to keyboard as well as clicking.

**Comment by merwok** [comment]
Thanks a lot for the example!

**Comment by matoni109** [comment]
Is this still the answer in 2022 ?

**Comment by marcoroth** [comment]
@matoni109 Currently yes, but there was some development going on in this area. Check out #442

**Comment by matoni109** [comment]
#442 looks like a great way forward, thanks for the update
