### ISSUE TITLE
Investigate streaming

### ISSUE THREAD

**Issue by david-a-wheeler** [stimulusjs/stimulus#132]
We started getting "too much memory" use messages.  We should track down what requests are causing that, but a likely solution is to force streaming.  See doc/design.md and this page:

https://medium.com/table-xi/stream-csv-files-in-rails-because-you-can-46c212159ab7

If we streamed out "big" files, then we wouldn't need to keep (big) things in memory.

**Comment by javan** [comment]
Is this a Stimulus issue?

**Comment by david-a-wheeler** [comment]
Drat, sorry, I meant this to apply to a different project. My apologies.
