### ISSUE TITLE
Submit event

### ISSUE THREAD

**Issue by jpic** [stimulusjs/stimulus#139]
Hello !

Is it possible to add support for the form submit event ?

Thanks !

**Comment by skyksandr** [comment]
Hi, can you say a bit more about it?

Default way of doing it through `data-action="submit->your_controller#your_action"` on form tag.
Isn't it works?

**Comment by jpic** [comment]
Ohoh that was a pebkac, using the proper data-action helps a lot, thanks a heap for your support.

Great framework, keep up the great work  !
