### ISSUE TITLE
targets aren't set when using <script type="text/template"></script>

### ISSUE THREAD

**Issue by marckohlbrugge** [stimulusjs/stimulus#143]
Using `<script type="text/template"></script>` seems to break Stimulus. Targets aren't accessible anymore. Likely related to #97

Example code: https://gist.github.com/marckohlbrugge/a38462ca6b900e3e7abb74c93f779913

Like in #97 `console.log(this.element.querySelectorAll("[data-target='hello.item']"));` does _not_ return the targets either.

**Comment by javan** [comment]
Yup, exact same as #97. Fixed already with #131 (will be released in v1.1).
