### ISSUE TITLE
Set the same value to a target defined multiple times on the page

### ISSUE THREAD

**Issue by eirvandelden** [stimulusjs/stimulus#145]
What I did:
- defined a `text` input with `data-target=jamming.solution`
- defined a `hidden` input with `data-target=jamming.solution`
- do `this.solutionTarget.value = 'foo'`

What I expected:
- `text` input to have value `foo`
- `hidden` input to have value `foo`

What I got:
- `text' input to have value `foo`
- `hidden` input to have *no value*

On StimulusJS 1.0.1 (and a Rails 5.1 app)

**Comment by skyksandr** [comment]
I believe you have to use plural form `this.solutionTargets` and iterate over like:
```
this.solutionTargets.forEach( (elem) => { elem.value = 'foo' } )
```

**Comment by javan** [comment]
@skyksandr is correct (thanks!)
