### ISSUE TITLE
Turbolinks duplicated requests

### ISSUE THREAD

**Issue by mbajur** [stimulusjs/stimulus#148]
Hello!

I'm playing around with Stimulus and i encountered a pretty bad blocker - each time i leave and get back to a page which uses stimulus controller, all the controller code gets duplicated. One reload = one replica. 

My controller periodically fetches stats and going to a different page and getting back on stats page 10 times makes the request duplicated 10 times - that's pretty bad.

You can see it here: https://mastodon-tags-explorer.hcxp.co/stats

Click on the `Instances` link and then again at `Stats` - you'll see that request to `/stats.json` is triggered two times per 10 seconds while it should be triggered once. Source code of this app is here: https://github.com/mbajur/mastodon-tags-explorer

Thanks in advance for any clues!

**Comment by javan** [comment]
That's correct. Your controller [starts a timer on `connect()`](https://github.com/mbajur/mastodon-tags-explorer/blob/fab2243a8635e57b9e20ed1709bfe979292d3690/app/javascript/controllers/stats_counters_controller.js#L6-L8), but doesn't stop it on `disconnect()` so it continues running. See https://stimulusjs.org/handbook/working-with-external-resources#releasing-tracked-resources.
