### ISSUE TITLE
ES6 syntax fails to compile in Rails application

### ISSUE THREAD

**Issue by ljachymczyk** [stimulusjs/stimulus#153]
Hi, 

Thank you for the great framework idea and implementation.

Stimulus works very well for me but I'm facing the problem described here: rails/webpacker#1285

That issue has been closed because it is "not an issue with webpacker". Perhaps this is the right place to discuss it?

**Comment by javan** [comment]
Sorry, but this isn't an issue with Stimulus. As I mentioned in https://github.com/rails/webpacker/issues/1285#issuecomment-368599568, I suspect it's caused by the Sprockets gem.
