### ISSUE TITLE
Capybara + Poltergeist Can't find variable: Set

### ISSUE THREAD

**Issue by blahutka** [stimulusjs/stimulus#154]
Hi, does anybody has the same issue with poltergeist throwing error `Can't find variable: Set`
It's in the stimulus code when it tries to call `new Set()`.

My setup is `webpacker` with Stimulus. In development it runs without problem. 
Does anybody knows how to fix this ?
Thank you

**Comment by javan** [comment]
See https://stimulusjs.org/handbook/installing#browser-support for a list of polyfills you may need to support older browser.
