### ISSUE TITLE
Cannot access actioned-element from event/action method

### ISSUE THREAD

**Issue by ngan** [stimulusjs/stimulus#158]
I have the follow scenario:

JS
```typescript
export default class extends Controller {
  public show(event) {
    // event is the MouseEvent
    // Have to no way in here to find the element that the action came from.
    // I'm trying to get the element's data-random's value (see below).
  }
}
```

HTML
```html
<body data-controller="foo">
  ...
  <button data-action="foo#show" data-random="value_for_controller">
    <i class="qrcode icon"></i>
  </button>
</body>
```

The button is 90% covered by the icon element, eg:
![image](https://user-images.githubusercontent.com/16579/40570130-83b567ba-603c-11e8-8a36-97265079e812.png)

If I click on the icon (the `<i>` element), my Foo controller will receive the event in the `show` function. However, the target of the event is the `<i>` element. I was expecting it to be the `button` element since that's where the `data-action` sits.

If this is intended behavior, what's the best way to get the `button` element (or the element that action was declared on)?

**Comment by javan** [comment]
`event.currentTarget` will always be the element with the action definition:

> Identifies the current target for the event, as the event traverses the DOM. It always refers to the element to which the event handler has been attached, as opposed to `event.target` which identifies the element on which the event occurred.

-- https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget

**Comment by ngan** [comment]
Thanks @javan! 🙇 

It's weird that `currentTarget` was showing as `null` when I print it out the event on console. But you're right, it evaluates to the `button` in code.
