### ISSUE TITLE
Turbolinks duplicate invoke

### ISSUE THREAD

**Issue by beviz** [stimulusjs/stimulus#160]
A simple test demo, it invoked multiple times `connect` function when Turbolinks changed pages. Is it a bug?

![stimulus-turoblinks](https://user-images.githubusercontent.com/1106312/40641225-72c5b56a-634b-11e8-8fa8-5823c578e103.gif)

layout:
```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <script src="stimulus.js"></script>
  <script src="turblinks.js"></script>
  <script src="start.js"></script>
<head>
<body>

</body>
</html>
```

a.html
```html
<div data-controller="hello">
  Page A
</div>
<a href="b.html">B</a>
```

b.html

```html
<div data-controller="hello">
  Page B
</div>
<a href="a.html">A</a>
```

start.js

```javascript
(() => {
  const application = Stimulus.Application.start()

  let count = 0
  application.register("hello", class extends Stimulus.Controller {
    connect() {
      console.log('controller connected', count++)
    }
  })
})()

Turbolinks.start()
```

**Comment by skyksandr** [comment]
AFAIK That's how Turbolinks works, first-time Turbolinks retrieve the page from cache, then loads from the server. If you'll setup conditional get using ETags + Last modified it won't update page if receive "304 Not modified" so you'll have only 1 connect when page retrieved from the cache.

So, I think, it's not a Stimulus issue.

**Comment by beviz** [comment]
@skyksandr Thanks for responding so quickly and clearly. 

So, I should decide to add `<meta name="turbolinks-cache-control" content="no-cache">` or not in Different scenarios.

**Comment by beviz** [comment]
Actually my real project problem is a Dropzone uploader container. it has 'data-exists-images' used to  add images to DOM. 

For instance I have 3 images and add them to DOM, when I go to another page and come back. 3 images already exists(Turbolinks cache) but the code will still be run to add 3 more images to DOM. now there are 6 images.

My solution is remove all exists images before add.

**Comment by skyksandr** [comment]
@beviz If I was facing the same issue as you I will subscribe to `turbolinks:before-cache` on `window` with parameter `{ once: true }` and do a teardown.

**Comment by beviz** [comment]
@skyksandr looks like add an `data-action` `turbolinks:before-cache` listener is more clearly, but every page which using this controller need to write it again, not worth.

**Comment by beviz** [comment]
Maybe this is the final solution: https://github.com/turbolinks/turbolinks/pull/390
