### ISSUE TITLE
Show example of multiple controllers on an element in the documentation

### ISSUE THREAD

**Issue by bolmaster2** [stimulusjs/stimulus#162]
It took a while for me to find out how to use multiple controllers on a single element as I can't find it documented anywhere. Maybe I'm just blind?

Let's say I have two controllers: `toggle` and `track` on the same element, you just separate them with an space:
```html
<a data-controller="toggle track" data-action="click->toggle#click click->track#click">
```

**Comment by javan** [comment]
It’s mentioned somewhat abstractly in The Handbook [here](https://stimulusjs.org/handbook/introduction#connecting-html-to-javascript):
> Stimulus works by continuously monitoring the page, waiting for the magic `data-controller` attribute to appear. Like the `class` attribute, you can put more than one value inside it. But instead of applying or removing CSS class names, `data-controller` values connect and disconnect Stimulus *controllers*.

We’ll consider adding a more concrete example next time we update the docs. Thank you for the feedback!
