### ISSUE TITLE
preventDefault not stopping propagation with remote link_to

### ISSUE THREAD

**Issue by MrHubble** [stimulusjs/stimulus#163]
**Problem**

Within a stimulus controller action, `event.preventDefault` is not stopping the ajax request created with `remote: true` from a `link_to` element

**Expected**

I would expect `event.preventDefault` to stop the ajax request as I believe it does with `button_to` etc.

**Sample code**

````erb
# index.erb
<%= link_to 'New Article', new_article_path, remote: true, data: {action: "hello#testPreventDefault"} %>
````

````js
//hello_controller.js
  testPreventDefault(event){
    event.preventDefault()
  }
````

**Output**

The logs show the `new` route is accessed even though `event.preventDefault()` is called:

<img width="1087" alt="screen shot 2018-07-12 at 7 25 59 pm" src="https://user-images.githubusercontent.com/2251631/42625496-3df57770-860b-11e8-9029-aa23661ebb42.png">

**Sample repo**

https://github.com/MrHubble/stimuluslinkto

**Comment by fourcube** [comment]
`event.preventDefault()` only prevents the link from being followed. `event.stopImmediatePropagation()` will stop the event from being propagated to other event handlers.

**Comment by MrHubble** [comment]
@fourcube thanks for taking the time to help.

With `event.stopImmediatePropagation()` the request still went through but this time as HTML rather than JS:

<img width="1282" alt="screen shot 2018-07-12 at 9 27 09 pm" src="https://user-images.githubusercontent.com/2251631/42630571-89b41a68-861a-11e8-9757-506ea72be95d.png">

**Comment by MrHubble** [comment]
@fourcube I think I must have misunderstood your answer. When I use both `preventDefault()` and `stopImmediatePropagation()` together it works which is what I think you were referring to. So the solution is

````js
  testPreventDefault(event){
    event.preventDefault()
    event.stopImmediatePropagation()
  }
````

Seems I have some reading to do. Thanks again.
