### ISSUE TITLE
Error connecting controller - property is null

### ISSUE THREAD

**Issue by almnes** [stimulusjs/stimulus#164]
I've been trying to debug this for a couple of hours, and I'm not able to figure this out.

I have a message_feed_controller.js, which has a method called resizeMessageContainer. That grabs the width and height of the view and sets the height and width accordingly.

```
initialize() {
  this.addResizeListener()
}

connect() {
    this.resizeMessageContainer()
}

 addResizeListener() {
   window.addEventListener('resize', this.resizeMessageContainer)
 }

resizeMessageContainer() {
  const fullHeight = window.innerHeight
  || document.documentElement.clientHeight
  || document.body.clientHeight;

  const width = window.innerWidth
  || document.documentElement.clientWidth
  || document.body.clientWidth;

  const height = fullHeight - 4

  const sidebarWidth = document.getElementById('messages__sidebar').offsetWidth
  const messageContainerWidth = (width - sidebarWidth)

  const feedContainerWidth = ((messageContainerWidth * 0.98) > 635) ? (messageContainerWidth * 0.98) : 635
  const feedFooterWidth    = ((messageContainerWidth * 0.96) > 360) ? (messageContainerWidth * 0.96) : 360

  document.getElementById('messages__feed').style.height           = `${height}px`;
  document.getElementById('messages__feed_container').style.width  = `${feedContainerWidth}px`;
  document.getElementById('messages__feed_footer').style.width = `${feedFooterWidth}px`;
}
```

my HTML looks like this:

```
<section id="messages__feed" data-controller="message-feed">
  <section id="messages__feed_container">
    <div id="messages__feed_items" data-target="message-feed.messages">
      <%= render @whole_feed %>
    </div>
  </section>

  <section id="messages__feed_footer" data-target="message-feed.footer">
    <%= render 'form', message: @message %>
  </section>
</section>
```

Now I keep getting the error

```
application.js:57 Error connecting controller
TypeError: Cannot read property 'style' of null
```

which refers to this line:
`document.getElementById('messages__feed_footer').style.width = `${feedFooterWidth}px`;`

now everything works fine if you refresh the page. However on the first load, this is what happens. I have tried to call it by id, and through target. Which both gives the same result. I tried to call it on connect instead of initialize, still nothing.

And now im left dumbfounded, and have no clue how this is happening. Any idea?

**Comment by ngan** [comment]
Try referencing your elements with target instead of getElementById. I see you have data-target already, why not use them?

**Comment by almnes** [comment]
@ngan I've tried that, it has the same outcome

**Comment by justinmetros** [comment]
When its all barebones vanilla JS it seems to work fine:
[JS Fiddle](https://jsfiddle.net/jmetros/5xhbenzu/)

Can you post a repro with stimulus running in it?

**Comment by javan** [comment]
That error stems from `document.getElementById()` returning `null` so it's not a Stimulus issue, technically. Feel free to repost your question on our community forum: https://discourse.stimulusjs.org/
