### ISSUE TITLE
[Question] How to add your polyfills

### ISSUE THREAD

**Issue by kud** [stimulusjs/stimulus#166]
Hello,

I'd like to know can I add these polyfills via your repo? https://github.com/stimulusjs/stimulus/tree/master/packages/%40stimulus/polyfills

I could add them one by one but I'd like to add it via your repo.

Thank you :)

**Comment by kud** [comment]
When searching on npm, I can see this

```
NAME                      | DESCRIPTION          | AUTHOR          | DATE       | VERSION  | KEYWORDS
stimulus                  | Stimulus JavaScript… | =javan…         | 2018-02-02 | 1.0.1    |
@stimulus/core            | Stimulus JavaScript… | =sstephenson…   | 2018-02-02 | 1.0.1    |
@stimulus/webpack-helpers | Stimulus JavaScript… | =sstephenson…   | 2018-01-30 | 1.0.0    |
@stimulus/mutation-observ | Practical wrappers…  | =sstephenson…   | 2018-01-30 | 1.0.0    |
ers                       |                      |                 |            |          |
@stimulus/multimap        | Multimap maps one…   | =sstephenson…   | 2017-12-29 | 0.9.0    |
@stimulus/test            | Stimulus JavaScript… | =sstephenson…   | 2018-02-02 | 1.0.1    |
```

It seems that "polyfills" isn't registered?

**Comment by javan** [comment]
The `@stimulus/polyfills` package will be published [with v1.1](https://discourse.stimulusjs.org/t/what-s-planned-for-stimulus-1-1/144) via https://github.com/stimulusjs/stimulus/pull/134

**Comment by kud** [comment]
Thank you :)

**Comment by Spone** [comment]
`v1.1.0-beta.1` is out! https://github.com/stimulusjs/stimulus/releases/tag/v1.1.0-beta.1
