### ISSUE TITLE
[Question] Is stimulusjs.org libre, including its design?

### ISSUE THREAD

**Issue by n2liquid** [stimulusjs/stimulus#167]
Hi, folks. Stimulus looks so nice and simple that it inspired me to make something similar this weekend, an SPA library called Junior (links FWIW => demo: https://n2liquid.github.io/junior/test.html, source: https://github.com/n2liquid/junior/blob/master/index.js).

I also really like stimulusjs.org's simple design and I think it would fit Junior well. Since I couldn't find the website's source repository anywhere, I have no idea what its license is. Could you clarify? Hopefully it has a nice libre license so I can copy it, sans the Basecamp logo and proprietary fonts of course.

(I'm pretty sure this isn't the right place to ask this, but then again what would've been the right place? :sweat_smile:)

**Comment by dhh** [comment]
Thanks! The website design is copyrighted and not released under an open license. You're free to be inspired, though.

**Comment by n2liquid** [comment]
Oh, bummer. Yeah, I'll do something along those lines... of source code. Just kidding :sweat_smile: But along those lines for sure :smile:
