### ISSUE TITLE
Your webpack-helper requires "controller" in the name, could be optional

### ISSUE THREAD

**Issue by kud** [stimulusjs/stimulus#168]
As you can see, we use the helper like this:

```
const context = require.context("./controllers", true, /\.js$/)
application.load(definitionsFromContext(context))
```

However, the regex isn't so explicit, as in the helper you still ask for a regex with `(_|-)controller`.

I'd like that that my javascript files do not have `controller` in the name.

For the moment I have to do

```
const application = Application.start()
application.register("Header", Header)
application.register("AboutPageTeamItem", AboutPageTeamItem)
```

But I'd like to use require.context to autoload these controlers.

Any help/adjustment?

**Comment by javan** [comment]
The webpack helpers are designed to work with [our suggested naming conventions](https://stimulusjs.org/handbook/installing#controller-filenames-map-to-identifiers).  See https://github.com/stimulusjs/stimulus/issues/70#issuecomment-359991756 too. Feel free to use the [`definitionsFromContext()`](https://github.com/stimulusjs/stimulus/blob/6946174b07b8891c8fab0ef7509842d950741c34/packages/%40stimulus/webpack-helpers/index.ts) helper as a starting point for writing your own if you prefer different conventions.

**Comment by kud** [comment]
This is what I thought to do. Thank you for your answer @javan :) and great framework by the way!
