### ISSUE TITLE
stimulusjs.org routinely offline

### ISSUE THREAD

**Issue by natecox** [stimulusjs/stimulus#169]
Hi, I'm trying to use the stimulus website as a reference point for a demo project, but I've found that the site has been offline multiple times over the last several days. 

It generally comes up again within a few moments, but it's extremely distracting.

**Comment by javan** [comment]
I've noticed this sporadically too and have no idea why it's happening. It's a normal static GitHub pages site proxied through https://fly.io/. Next time it's unreachable for you, try doing a DNS lookup:
```
$ dig stimulusjs.org

; <<>> DiG 9.10.6 <<>> stimulusjs.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3073
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;stimulusjs.org.			IN	A

;; ANSWER SECTION:
stimulusjs.org.		294	IN	A	206.51.242.1

;; Query time: 20 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Thu Jul 26 01:51:33 EDT 2018
;; MSG SIZE  rcvd: 59
```
Also check if https://stimulusjs.github.io/ and https://dk3nyev8cy7dpwe4.shw.io/ are loading.

As a fallback, you can always browse the handbook pages on GitHub: https://github.com/stimulusjs/stimulus/tree/master/handbook

**Comment by natecox** [comment]
Site is down again now. Here's the result of a dig:

```
•100% ➜ dig stimulusjs.org

; <<>> DiG 9.10.6 <<>> stimulusjs.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43594
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;stimulusjs.org.			IN	A

;; ANSWER SECTION:
stimulusjs.org.		300	IN	A	206.51.242.1

;; Query time: 18 msec
;; SERVER: 192.168.11.1#53(192.168.11.1)
;; WHEN: Thu Jul 26 12:39:01 PDT 2018
;; MSG SIZE  rcvd: 59
```

Both https://stimulusjs.github.io/ and https://dk3nyev8cy7dpwe4.shw.io/ load properly, even while https://stimulusjs.org/ is offline.

Here's a dig for the github.io page:
```
•100% ➜ dig https://stimulusjs.github.io/

; <<>> DiG 9.10.6 <<>> https://stimulusjs.github.io/
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 40377
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;https://stimulusjs.github.io/.	IN	A

;; AUTHORITY SECTION:
.			3951	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2018072601 1800 900 604800 86400

;; Query time: 23 msec
;; SERVER: 192.168.11.1#53(192.168.11.1)
;; WHEN: Thu Jul 26 12:40:20 PDT 2018
;; MSG SIZE  rcvd: 133
```

I'm curious as to why you're doing a redirection through fly.io if the site is a github pages page, considering you can use a custom domain with github directly. I'd never seen the service before, does it do something special?

**Comment by javan** [comment]
fly.io does a lot of cool things, but we only use it for SSL (the site before GitHub pages supported SSL for custom domains).

**Comment by javan** [comment]
The domain's pointed at GH pages directly now. Hopefully that fixes the sporadic unreachability. 🙏
