### ISSUE TITLE
null: 'MutationObserver' is undefined

### ISSUE THREAD

**Issue by leoliu** [stimulusjs/stimulus#174]
I am using `1.1.0-beta.1` and have imported @stimulus/polyfills. I am getting a crash from some user like this:

```
null: 'MutationObserver' is undefined
  at ? (/assets/js/main-916d7d638c.js:1:10241)
```

The user agent is:

Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.0; Trident/6.0; IEMobile/10.0; ARM; Touch; Microsoft; Lumia 535 Dual SIM)

ideas?

**Comment by javan** [comment]
IE 10 isn't officially supported by Stimulus, and the `@stimulus/polyfills` package only [provides support down to IE 11](https://github.com/stimulusjs/stimulus/blob/8c1d115e73330b2805e67e32ccdf233dc7544930/handbook/06_installing_stimulus.md#supporting-older-browsers):
> Stimulus supports all evergreen, self-updating desktop and mobile browsers out of the box. If your application needs to support older browsers, like Internet Explorer 11 or older versions of Safari, you can use the @stimulus/polyfills package to polyfill the required browser APIs.

**Comment by leoliu** [comment]
Thanks for the info.

**Comment by javan** [comment]
You might be able to get it working in IE 10 with additional polyfills. Here are few resoures:
- https://github.com/webcomponents/webcomponentsjs/blob/v0.7.24/MutationObserver.js
- https://github.com/zloirock/core-js
- https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-Browser-Polyfills#dom--events
- https://polyfill.io/v2/docs/

**Comment by leoliu** [comment]
Excellent and thanks again.

**Comment by phoet** [comment]
@leoliu could you give an example of how you fixed it?

**Comment by leoliu** [comment]
@phoet, I ignore the issue because users using ie < 11 are so rare it is not worth fixing for me.
