### ISSUE TITLE
Doesn't work with https://polyfill.io's Array.from

### ISSUE THREAD

**Issue by danwhite85** [stimulusjs/stimulus#175]
We're using https://polyfill.io in our project instead of @stimulus/polyfills. Everything seems to work except for Array.from. 

Is it possible to make stimulus compatible with polyfill.io's version.

**polyfill.io**
https://github.com/Financial-Times/polyfill-service/blob/master/packages/polyfill-library/polyfills/Array/from/polyfill.js

**core-js**
https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/es.array.from.js

**Comment by sstephenson** [comment]
Can you be more specific about the ways in which it doesn't work? What errors do you see, if any, and in what browsers?

**Comment by danwhite85** [comment]
IE 11. No errors are logged. I found a number of open issues on their tracker, so it's likely an issue with their polyfill. I'll just include core-js's version until they're resolved. Thanks
