### ISSUE TITLE
Creating a modal controller causes connect to fire infinitely

### ISSUE THREAD

**Issue by abepark01** [stimulusjs/stimulus#179]
Hello,  
I am using Foundation Zurb's reveal modal; it works similar to https://github.com/stimulusjs/stimulus/issues/73 in that when a modal is initialized it gets added to the bottom of the body tag.

What I am noticing is that when I setup the modal in the init function the connect function is getting called infinitely until the page crashes.

Has anyone had success making a modal controller?
It seems like most modals used the portal pattern where the markup you used to set up the modal gets moved to the body.

**controllers/members-modal.js**
```
/* global Foundation */
import { Controller } from 'stimulus';

export default class extends Controller {
  initialize() {
    this.modal = new Foundation.Reveal($(this.element), {});
  }

  connect() {
     console.log('connect');
  }
}
```

```
<div class="section" data-controller="members-modal">
  <h4>Modal</h4>
</div>
```

**Comment by javan** [comment]
> the connect function is getting called infinitely until the page crashes

Based on that I'm guessing `new Foundation.Reveal` clones the element you pass in. You could try using a child target element instead.

> Has anyone had success making a modal controller?

Our community forum is the best place to ask questions like this. https://discourse.stimulusjs.org/
