### ISSUE TITLE
Window actions do not work with multiple instances

### ISSUE THREAD

**Issue by danwhite85** [stimulusjs/stimulus#181]
It appears that window actions like `resize@window->{controller}#windowResize` do not work with multiple instances of the component/controller. The `windowResize` function only gets called for the last instance in the page. Hope that makes sense.

**Comment by javan** [comment]
Do you mean `increment()` is only called on the controller instance for the 2nd element in HTML like this?
```html
<div data-controller="counter"
     data-action="resize@window->counter#increment"></div>

<div data-controller="counter"
     data-action="resize@window->counter#increment"></div>
```
It works as expected in this example: https://codepen.io/javan/pen/MqKgEw/?editors=1010#0 (resize the window)

**Comment by danwhite85** [comment]
Looks like it's actually my debounce decorator. Any reason this would cause it to only work on the last instance?

```
import _debounce from 'lodash/debounce';

export default function(wait) {
  return function(target, name, descriptor) {
    const { value } = descriptor;

    if (typeof value === "function") {
      descriptor.value = _debounce(value, wait);
    }

    return descriptor;
  };
}
```

```
@debounce(250)
windowResize() {
  // do resize stuff
}
```

**Comment by javan** [comment]
I'm not sure. That works fine when compiled by TypeScript: https://codepen.io/javan/pen/QVyyRJ?editors=1010#0

Perhaps the build tool and/or decorator plugin you're using isn't doing what you expect? Try without the decorator and see if that works: https://discourse.stimulusjs.org/t/throttle-inside-a-controller/100/2

**Comment by danwhite85** [comment]
Works using the initialize method without the decorator. Will look into plugin I'm using. Thanks
