### ISSUE TITLE
Comunicating data between controllers

### ISSUE THREAD

**Issue by kinnrot** [stimulusjs/stimulus#183]
I have a "best practice question"

Lets say I have a reusable modal dialog that got a text input.
I'd like every other component/controller, to be able to show this dialog and receive a callack/promise with the result (dismissed/entered input value), once dialog closed.

I think it's a common case which has several ways to implement, I'd like to know how you guys think it should go, 

thanks

**Comment by sstephenson** [comment]
Hello! 

In general, questions like these are better suited for our [community forum](https://discourse.stimulusjs.org).

See #35 for a previous discussion on the same topic.
