### ISSUE TITLE
Homepage hits you like a bus 🚌 in 4k

### ISSUE THREAD

**Issue by davegson** [stimulusjs/stimulus#185]
![stimulusjs org in 4k](https://user-images.githubusercontent.com/3080765/44784194-511dc500-ab7c-11e8-9597-29b5c2bc5170.png)

It does not seem that modest in that instance. I'd suggest adding a container ;)

Thanks for the framework!
Cheers

**Comment by javan** [comment]
The layout and typography intentionally scale relative to the viewport. 

I’d suggest being more considerate than “hits you like a bus” when critiquing someone’s work.
