### ISSUE TITLE
[question] Yarn package dependencies

### ISSUE THREAD

**Issue by thomasdarde** [stimulusjs/stimulus#186]
This how I have stimulus dependency listed in my "package.json":

`"stimulus": "~1.0.1"`

but it does install @stimulus/core version 1.1.0 with a yarn upgrade

```
dependencies:
    "@stimulus/core" "^1.0.1"
    "@stimulus/webpack-helpers" "^1.0.0"
```

instead of ?

```
dependencies:
    "@stimulus/core" "~1.0.1"
    "@stimulus/webpack-helpers" "~1.0.0"
```

I'm not sure it's an issue or an intended behaviour but seems relevant to ask.

**Comment by sstephenson** [comment]
Hi there! I don't believe this is a Stimulus issue. You might want to check the [Yarn documentation](https://yarnpkg.com/en/docs/cli/upgrade) or post a question on our [community forum](https://discourse.stimulusjs.org).
