### ISSUE TITLE
Add link from documentation to SECURITY.md

### ISSUE THREAD

**Issue by david-a-wheeler** [stimulusjs/stimulus#187]
There should be a link from somewhere in the handbook to SECURITY.md.

[PR 184](https://github.com/stimulusjs/stimulus/pull/184/files) added a new SECURITY.md document, which is good, but the handbook (the "normal" starting documentation) never points users to it.  Since essentially 100% of developers should care about security, never mentioning the security information is a big problem.

One obvious place is at the end of "4: Managing State".  E.g., after this text:

> Now our controller’s state lives entirely in the DOM.

Add something like this:

> Of course, if an attacker can manipulate the DOM a page, the attacker can modify controller state in the DOM or the data-action attribute.  For more about how to use stimulus securely, see [SECURITY.md](security.md).

It doesn't need to be *there* or have that text - there just should be *some* link from the handbook to the security page, and a hint to the reader that it'd be worth seeing.

**Comment by jeremy** [comment]
Great suggestion for wording and placement.

> essentially 100% of developers should care about security, never mentioning the security information is a big problem

A handbook callout is a good idea; we needn't overstate the case for it. The GitHub repo is a primary entry point for Stimulus and a conventional ALLCAPS file is [precisely the callout that developers look for](https://www.google.com/search?q=security.md+site%3Agithub.com), much like the code of conduct and changelog.

**Comment by odiegosantos** [comment]
All's Good!

**Comment by sstephenson** [comment]
GitHub has since added a Security tab to the repo which displays the contents of our SECURITY.md front and center: https://github.blog/changelog/2019-05-23-security-policy/

I don’t think a security call-out in the Managing State section of the handbook is appropriate, and I don’t think security deserves its own chapter there or in the reference, so I’m going to close this issue for now.
