### ISSUE TITLE
Typescript definition Controller.element should be HTMLElement

### ISSUE THREAD

**Issue by tpetry** [stimulusjs/stimulus#189]
I don't know whether it is intended or a bug. But at the moment the `controller.d.ts` definition defines `readonly element: Element` which means many dom interactions are not possible without tricking typescript that the element property is in reality a `HTMLElement` object.

**Comment by javan** [comment]
It's intentional since Stimulus supports non-`HTMLElement`s like `SVGElement`. For example, the same controller would work with both of these elements:

```html
<svg data-controller="hello">
  <a data-action="hello#greet" href="#">
    <circle cx="20" cy="20" r="20">
  </a>
</svg>

<div data-controller="hello">
  <a data-action="hello#greet" href="#">
    👋
  </a>
</div>
```

> which means many dom interactions are not possible

What `HTMLElement` APIs are you using, specifically?

**Comment by tpetry** [comment]
Ah you're right, thats a good reason. The problem with TypeScript is just that you have to use different types of elements all the time, with the added boilerplate code of adding type definition for the targets. A better typescript solution instead of the following would be nice:
```ts
export default class extends Controller {
  private hasSomeTarget!: boolean;
  private someTarget!: HTMLElement;
  public static targets = [
    "some",
  ];
```

**Comment by leevigraham** [comment]
Ran into a similar problem trying to add an `click` hander to `this.element`. Is there anyway to change the type of `this.element` if you know it's always going to be a `HTMLElement`?

**Comment by Sub-Xaero** [comment]
You can just cast it.

```typescript
(this.element as HTMLElement).addEventListener('click' ...)
```
