### ISSUE TITLE
Stimulus creates additional assets when building with Webpack

### ISSUE THREAD

**Issue by robinvdvleuten** [stimulusjs/stimulus#191]
Whenever I build the assets through `rails assets:precompile`, Webpacker compiles all packs as expected. But I also receive an additional `public/assets/@stimulus/core/dist/src/application-...js` somehow. Is this something I need to configure with Stimulus?

**Comment by javan** [comment]
I'm pretty sure that's an issue with Sprockets. See https://github.com/stimulusjs/stimulus/issues/153#issuecomment-385392326 → https://github.com/rails/webpacker/issues/1285#issuecomment-368599568
