### ISSUE TITLE
Stimulus nested controller scopes ignores event bubbling order without data-target 

### ISSUE THREAD

**Issue by PFWhite** [stimulusjs/stimulus#196]
I have a self nested controller responsible for toggling classes to show and hide elements. The toggle function iterates through all immediate child elements and calls `child.classList.toggle('hide')` and stops event propagation. The `.hide` class just sets display to none. My markup is as follows.
```
<div data-controller="toggler">
    <div data-action="click->toggler#toggle">
    first controller first screen
    </div>
    <div class="hide">
    first controller second screen
        <div data-controller="toggler">
            <div data-action="click->toggler#toggle">
            second controller first screen
            </div>
            <div class="hide">
            second controller first screen
            </div>
        </div>
    </div>
</div>
```

How I would expect this to work is that initially you see the `first controller first screen`. Clicking on that element hides `first controller first screen` then shows `first controller second screen` and `second controller first screen`. Then when clicking the div element in the second controller's scope you would see `first controller second screen` and `second controller second screen`. 

What actually happens is that, the click in the child toggler controller's div is being handled by the parent controller. It then displays `first controller first screen` and never calls the child controller's method.

I would expect that events bubble through controller scopes like how events bubble out/up through DOM elements and that I could stop their propagation the same way. I realize that I could fix this by changing some things, but it is very strange that scopes work opposite event propagation.

I am on version 1.1.0

**Comment by sstephenson** [comment]
I think what's happening is that the inner controller correctly handles the click event, and then the same event bubbles up to the outer controller, causing it to toggle, too.

If so, you probably just want to stop the event from bubbling in the `toggle` method:
```js
  toggle(event) {
    // ...
    event.stopPropagation()
  }
```

**Comment by PFWhite** [comment]
It was not. I had a breakpoint inside the handler and it triggered one time and the element on which it triggered was the parent controller. It never triggered for the child.

**Comment by PFWhite** [comment]
I'm sorry I missed an extra "l" in my data controller attribute. Closing as this works just fine
