### ISSUE TITLE
Website: size of fonts

### ISSUE THREAD

**Issue by kud** [stimulusjs/stimulus#198]
Hello,

I'd just like to say that the font-size of the homepage (https://stimulusjs.org/) is way too big.

<img width="2160" alt="image" src="https://user-images.githubusercontent.com/655838/47207519-b0819f80-d38b-11e8-8aac-16c49674f20f.png">

Plus, the unzoom/zoom only works on a part of the website, this one:

>  Stimulus is a JavaScript framework with modest ambitions. It doesn’t seek to take over your entire front-end—in fact, it’s not concerned with rendering HTML at all. Instead, it’s designed to augment your HTML with just enough behavior to make it shine. Stimulus pairs beautifully with Turbolinks to provide a complete solution for fast, compelling applications with a minimal amount of effort.

The rest of the website is (un)zoomable.

It could be great to use `(r)em` for the font-size and adjust this to the resolution of the screen. :)

**Comment by javan** [comment]
Thanks, we made a few adjustments.

> I'd just like to say that the font-size of the homepage (https://stimulusjs.org/) is way too big.

Ditto for your browser window!

**Comment by kud** [comment]
Thank you @javan :)
