### ISSUE TITLE
I can use Stimulus with Python Flask

### ISSUE THREAD

**Issue by mrmetech** [stimulusjs/stimulus#199]
Hi i can only find Stimulus being used with Ruby so i wanted to ask if it would work with flask too

**Comment by savroff** [comment]
@mrmetech sure, it will work just fine.

**Comment by mrmetech** [comment]
Ok thanks just making sure as i could only find it being used with ruby
thanks

**Comment by javan** [comment]
Yes, Stimulus is just a JavaScript library.
