### ISSUE TITLE
Proposal: Add Stimulus event to listen to addition/removal of targets

### ISSUE THREAD

**Issue by ernsheong** [stimulusjs/stimulus#200]
I am looking for a way to listen to events for addition or removal of controller targets.

Use case: When new targets appear in the DOM, I want to trigger an action/DOM manipulation.

Why: My controller sits at the top level (document body). I suppose the recommended use case is to scope it to a specific DOM subtree, but in this case it is meant to manage DOM everywhere so it resides in the body

**Comment by skyksandr** [comment]
My approach would be to create a controller for this specific targets and let them emits an event in `connect`.
Also, you can pass any required data in `CustomEvent`.

**Comment by ernsheong** [comment]
Yes, but event emitted in `connect()` is only the first time, what if more targets are added later on, just targets mind you, no new controllers.

**Comment by skyksandr** [comment]
What I was saying in other words - let targets emit events.

**Comment by sstephenson** [comment]
Thanks for the suggestion! This is something that's on our radar.

For now, I would echo @skyksandr's recommendation to add a new `data-controller` annotation to each target element you want to observe. Those elements can still serve as targets for your outer controller. For example:

```html
<body data-controller="outer">
  ...
  <!-- Some newly inserted targets: -->
  <div data-target="outer.thing" data-controller="inner">1...</div>
  <div data-target="outer.thing" data-controller="inner">2...</div>
</body>
```

Each target has its own `inner` controller, which emits an `inner-connected` event when connected:

```js
// inner_controller.js
export default class extends Controller {
  connect() {
    const event = document.createEvent("CustomEvent")
    event.initCustomEvent("inner-connected", true, true, null)
    this.element.dispatchEvent(event)
  }
}
```

Add a `data-action` to the body element to call the `thingConnected()` method in response to those events:

```html
<body data-controller="outer" data-action="inner-connected->outer#thingConnected">
   ...
```

```js
// outer_controller.js
export default class extends Controller {
  static targets = [ "thing" ]

  thingConnected(event) {
    console.log(event.target) // the element that was just connected
  }
}
```

Closing this issue for now, but please feel free to continue discussing it over on [the community forum](https://discourse.stimulusjs.org/).

**Comment by brendon** [comment]
I found that the `outer` listener doesn't catch the event if it's fired as part of the `connect()` function of the `inner`. The event gets caught just fine later on though.

**Comment by brendon** [comment]
This is why it wasn't catching the event. Wrapping the dispatch in a promise fixed it. Feels dirty :)

https://github.com/stimulusjs/stimulus/issues/201#issuecomment-435285227

**Comment by brendon** [comment]
This (https://github.com/stimulusjs/stimulus/issues/222) fixed my particular problem and I was able to remove the resolved promise.

**Comment by benbonnet** [comment]
as of today 

```
export default class extends Controller {
  static targets = [ "thing" ]

  thingTargetConnected(event) {
    console.log(event.target) // the element that was just connected
  }
}
```
