### ISSUE TITLE
disconnect/connect not firing after data-controller is changed

### ISSUE THREAD

**Issue by richardkmiller** [stimulusjs/stimulus#204]
Hello! I did a personal deep dive on Stimulus yesterday and I'm really liking it.

FWIW, it appears that removing and re-adding the `data-controller` attribute on an existing element did not cause the `connect` and `disconnect` methods to be called. Am I missing anything here?

The docs say this should be among the reasons for `disconnect()` to be called, i.e. "[the element’s data-controller attribute is removed or modified](https://stimulusjs.org/reference/lifecycle-callbacks#disconnection)".

I started with the Glitch demo and defined `connect()` and `disconnect()` in `hello_controller.js`:
```javascript
  connect() {
    console.log("Hello!")
  }
  disconnect() {
    console.log("Goodbye!")
  }
```

 I added the following body to `index.html`:
```html
<body>
  <div id="hello" data-controller="hello"></div>
  <button>Replace controller</button>
</body>
```

I added the following to `index.js` to trigger the change (delete and re-add) on the `data-controller` attribute:
```javascript
document.querySelectorAll('button')[0].addEventListener('click', function() {
  console.log("Replacing data-controller attribute");
  document.getElementById('hello').setAttribute('data-controller', '');
  document.getElementById('hello').setAttribute('data-controller', 'hello');
});
```

In the console I see "Hello!" when the script first loads, but I don't see it when I click the "Replace controller" button like I would expect.

Here's the Glitch link if it helps:
https://glitch.com/edit/#!/zealous-vole-1?path=src/index.js:13:0

Thanks!

**Comment by javan** [comment]
Synchronously removing and restoring an attribute is the same as not changing it as far as the DOM is concerned ([more on that](https://www.youtube.com/watch?v=cCOL7MC4Pl0), if you're interested).

If you defer restoring the attribute, you'll see the results you expect:
```js
document.getElementById('hello').setAttribute('data-controller', '');
setTimeout(function() {
  document.getElementById('hello').setAttribute('data-controller', 'hello');
})
```
https://glitch.com/edit/#!/denim-engineer?path=src/index.js:13:4
https://denim-engineer.glitch.me/

**Comment by richardkmiller** [comment]
@javan Got it! That's helpful for understanding what's going on here. Thank you!
