### ISSUE TITLE
Should replacing the controller element fire disconnect and connect events?

### ISSUE THREAD

**Issue by Abduvakilov** [stimulusjs/stimulus#205]
I have a [selecter](https://github.com/Mobius1/Selectr) controller which is calling connect-disconnect-connect from the start because the plugin is appending the controller element to its generated node.
I have created an example below to explain the issue. The `append` method causing the controller to disconnect and connect. Is it intended behavior?
[The Example](https://jsfiddle.net/xL2uov9s/)

**Comment by javan** [comment]
Yes, that's expected:

> [**Reconnection**](https://stimulusjs.org/reference/lifecycle-callbacks#reconnection)
>
> A disconnected controller may become connected again at a later time.
>
> When this happens, such as after removing the controller’s element from the document and then re-attaching it, Stimulus will reuse the element’s previous controller instance, calling its `connect()` method multiple times.
