### ISSUE TITLE
How to handle outside click with Stimulus

### ISSUE THREAD

**Issue by devkir** [stimulusjs/stimulus#208]
Hello!
I am struggling managing how to handle outside click to close open dropdown for example.
Are you using global event listeners at Basecamp to handle outside clicks on dropdowns?

**Comment by pascallaliberte** [comment]
The best way is to use the `@window` context for the click action 

e.g. `click@window->dropdown#hide` in the example below

```html
<nav data-controller="dropdown">
  <button
   data-action="click->dropdown#toggle click@window->dropdown#hide"
   data-target="dropdown.button">
    Menu
  </button>
</nav>
```

**Comment by devkir** [comment]
@pascallaliberte Thanks it works!
```
<nav data-controller="dropdown" data-target="dropdown.wrapper">
  <button
   data-action="click->dropdown#toggle click@window->dropdown#hide"
   data-target="dropdown.button">
    Menu
  </button>
</nav>
```

```
hide() {
    event.preventDefault()
    if (!this.wrapperTarget.contains(event.target)) {
      this.contentTarget.classList.add("hidden")
    }
 }
```

I have added `wrapper` target to allow clicks in dropdown itself.
Stimulus is ❤
