### ISSUE TITLE
Controllers don't reconnect after DOM mutations triggered by Morphdom

### ISSUE THREAD

**Issue by hopsoft** [stimulusjs/stimulus#209]
This may not be an issue with Stimulus but I wanted to bring it to your attention. I've noticed that Stimulus doesn't appear to recognize DOM mutations triggered by [Morphdom](https://github.com/patrick-steele-idem/morphdom).

I have a work around inspired by a conversation on a [different issue](https://github.com/stimulusjs/stimulus/issues/204).

```javascript
import { Controller } from "stimulus"

export default class extends Controller {
  connect() {
    this.name = this.element.dataset.controller;
    document.addEventListener('cable-ready:after-morph', this.reconnect.bind(this));
  }

  reconnect() {
    setTimeout(() => this.element.setAttribute('data-controller', this.name), 1);
    this.element.setAttribute('data-controller', '');
  }
}
```

For more context see: https://github.com/hopsoft/cable_ready#stimulus-gotchas

_Note that adding the event listener for each connect is problematic. My actual project guards against adding redundant listeners._

**Comment by javan** [comment]
Are you mutating the DOM in such a way that the controller's element gets reconnected? Or, are you expecting another `connect()` after every document mutation (hence the global `document` listener)?

> When this happens, such as after removing the controller’s element from the document and then re-attaching it, Stimulus will reuse the element’s previous controller instance, calling its `connect()` method multiple times.
> ↳ https://stimulusjs.org/reference/lifecycle-callbacks#reconnection

**Comment by hopsoft** [comment]
My use case renders an HTML table (with a Stimulus controller) that has draggable rows. The drag/drop behavior is initialized in the table's `connect`. The user interacts with the table and it get re-rendered server side but Morphdom only applies the diff for DOM mutations. In this case it was only a few rows. That's why the table doesn't `connect` after the DOM update. Unfortunately drag/drop stops working for all rows when this happens.

I suspect that moving the row drag/drop event listener initialization to Stimulus actions may work. I'll try that and will report back shortly.

**Comment by hopsoft** [comment]
Verified that initializing drag/drop with Stimulus actions works and is the correct way to handle this scenario.

To be clear. I __removed__ the drag/drop initialization from the table's connect method.

```javascript
// app/javascript/controllers/table_controller.js
import { Controller } from 'stimulus';

export default class extends Controller {
  connect() {
    let rows = this.element.querySelectorAll('tr[draggable]');
    rows.forEach(tr => {
      tr.addEventListener('dragstart', this.dragStart);
      tr.addEventListener('dragend', this.dragEnd);
      tr.addEventListener('dragover', this.dragOver);
      tr.addEventListener('drop', this.drop);
    });
  }

  // ...
}
```

And I __added__ Stimulus actions to each individual row.

```html
<table data-controller="table">
  <tr draggable 
    data-action="table#dragStart table#dragEnd table#dragOver table#drop">
    ...
  </tr>
</table>
```

Thanks for being patient, letting me talk this out, and find the right solution.

**Comment by javan** [comment]
> And I added Stimulus actions to each individual row.

Nice! That's the Stimulus Way™ ;)

BTW, your action descriptors are missing event names:
```html
 <tr draggable data-action="dragstart->table#dragStart dragend->table#dragEnd …">
```

**Comment by hopsoft** [comment]
Oh whoops. I updated my example for posterity ;-)
