### ISSUE TITLE
How to build for production when using in a non-Rails project?

### ISSUE THREAD

**Issue by DevotionGeo** [stimulusjs/stimulus#210]

**Comment by danielcompton** [comment]
This is a usage question and should go to https://discourse.stimulusjs.org/, I think?

**Comment by DevotionGeo** [comment]
thank you!
So far I always used create-react-app or vue-cli for those projects. :)
Looks like this time I have to learn some bundler like webpack, or parcel and sort this out myself, because nobody responded to that question at the forum.

**Comment by DevotionGeo** [comment]
I made it work by adding `"build": "webpack --mode production"` to `"scripts"` inside `package.json`, then running `yarn build`.
It was so easy.
