### ISSUE TITLE
Support for select2 event

### ISSUE THREAD

**Issue by msz2017** [stimulusjs/stimulus#211]
$('#mySelect2').on('select2:select', function (e) {
  // Do something
});

**Comment by adrienpoly** [comment]
Select2 does not fire native events. To use select2 with stimulus you must convert the select2 events to native events

Here are several resources :
- https://discourse.stimulusjs.org/t/how-to-use-stimulus-inside-bootstraps-popovers/177/3
- https://dev.to/dstull/stimulus-with-turbolinks-select2-and-formvalidation-1i7l
- https://github.com/pascallaliberte/stimulus-turbolinks-select2

In general, for support questions the community forum is a better place:
https://discourse.stimulusjs.org/
