### ISSUE TITLE
links to the CI

### ISSUE THREAD

**Issue by matthewmueller** [stimulusjs/stimulus#212]
I noticed that you're running stimulus against a bunch of CI providers which is awesome. Are there any links where I can see the test results?

**Comment by javan** [comment]
Click on the green check mark next to [each commit](https://github.com/stimulusjs/stimulus/commits/master):
![screen shot 2018-12-12 at 8 38 16 am](https://user-images.githubusercontent.com/5355/49873356-a60edf80-fde9-11e8-82e7-26e65bf45f7a.png)

The test suite currently runs on CircleCI: https://circleci.com/gh/stimulusjs/stimulus

**Comment by matthewmueller** [comment]
ahh got it, thanks!
