### ISSUE TITLE
How to add the polyfills without a build system?

### ISSUE THREAD

**Issue by jingyulong** [stimulusjs/stimulus#219]
I want to use stimulus in my .net MVC project, and I don't want to use any build system to make the project more complexity. And I see the doc use npm to add polyfills.
- Is there a way to add the polyfills without a build system?
- Is there any best practice for the project without a build system?

Thanks in advance,
Jing Yulong

**Comment by justinmetros** [comment]
You can look into something like [Polyfill.io](https://polyfill.io/v3/)

Will let you generate a script tag from a CDN that has what you need.

**Comment by jingyulong** [comment]
@justinmetros Thanks for posting, it works for me.

**Comment by Szymon-dziewonski** [comment]
@justinmetros it is not working :(

```
/* Polyfill service v3.40.0
 * For detailed credits and licence information see https://github.com/financial-times/polyfill-service.
 * 
 * Features requested: Array.from,Array.prototype.find,Array.prototype.findIndex,Array.prototype.map,Element.prototype.closest,MutationObserver,Object.assign,Promise,Set
 *  */


/* No polyfills found for current settings */
```

**Comment by timrwilliams** [comment]
Polyfill.io will only return the polyfills required for your browser so if you hit that link in Chrome for example you'll get back an empty response.

Add an extra param of `flags=always` to get the full package:

https://polyfill.io/v3/polyfill.min.js?features=default%2CArray.prototype.find%2CArray.prototype.findIndex%2CArray.from%2CMap%2CObject.assign%2CPromise%2CSet%2CElement.prototype.closest%2CMutationObserver&flags=always
