### ISSUE TITLE
babel-runtime error

### ISSUE THREAD

**Issue by sabeurthabti** [stimulusjs/stimulus#22]
`Uncaught SyntaxError: Unexpected identifier`

![screen shot 2017-12-31 at 00 18 15](https://user-images.githubusercontent.com/2606228/34458166-29b859b4-edc0-11e7-8811-3700e216ef6d.jpg)

I am not sure if this is a stimulus issue, I am using https://github.com/parcel-bundler/parcel and it the bundle keeps complaining that it cannot find `babel-runtime/...`. I do have that module within my node_modules

**Comment by javan** [comment]
I just tried using parcel with Stimulus and it worked without error. Can you share a minimal example app that reproduces the issue?

**Comment by javan** [comment]
Seems like this is a parcel and/or babel issue? https://github.com/parcel-bundler/parcel/issues/408#issuecomment-354594339

Feel free to reopen if you can isolate a Stimulus-specific problem.

**Comment by sabeurthabti** [comment]
@javan thanks for taking time with this, I have managed to resolve the issue by removing the `.cache` folder generated by parcel. Hopefully, this would help someone else in the future.
