### ISSUE TITLE
event.currentTarget is null

### ISSUE THREAD

**Issue by ocarreterom** [stimulusjs/stimulus#224]
In this scenario:
```html
<div data-action="click->controller#action">
  <div>Title</div>
  <div>Description</div>
</div>
```
```js
action (event) {
  event.target // Title or Description element
  event.currentTarget // always null
}
```
I can't get the element which event was added.

**Comment by javan** [comment]
Hmm, can you share the exact code you're using? It works as expected in this demo: https://codesandbox.io/s/ov16ky7yp5?expanddevtools=1

**Comment by ocarreterom** [comment]
Sorry, it's working ok. DevTools confused me 😭 
![captura de pantalla 2019-01-30 a las 18 05 43](https://user-images.githubusercontent.com/11599942/51998911-e15c8f00-24b9-11e9-91be-b1cf9bea380d.png)
Loggin the event in devtools shows `currentTarget` null.
https://codesandbox.io/s/6zv485xzok

**Comment by javan** [comment]
Ah, yes, `event.currentTarget` changes as the event bubbles up so it will be `null` if you save a reference to the `event` and inspect it later.
