### ISSUE TITLE
Does IE11 need @stimulus/polyfills in addition to babel-polyfill?

### ISSUE THREAD

**Issue by airblade** [stimulusjs/stimulus#227]
I have a Rails 5.2.x app using Webpacker 3.5.x and Stimulus 1.1.1.

At the top of my `packs/application.js` is `import 'babel-polyfill'`.

The [Stimulus Handbook](https://stimulusjs.org/handbook/installing#browser-support) says:

> If your application needs to support older browsers like Internet Explorer 11, include the @stimulus/polyfills package before loading Stimulus.

Do I need to do that if I'm already importing Babel's polyfill?

Many thanks in advance!

**Comment by sstephenson** [comment]
The [@stimulus/polyfills README](https://github.com/stimulusjs/stimulus/tree/master/packages/%40stimulus/polyfills) describes exactly which functions need to be polyfilled for IE 11. I’m afraid I don’t know whether babel-polyfill covers those or not—the [community forum](https://discourse.stimulusjs.org) would probably be a better place to ask questions about third-party libraries.
