### ISSUE TITLE
Simple form and Stimulus

### ISSUE THREAD

**Issue by crojasu** [stimulusjs/stimulus#228]
Hi to all, 

I am trying to do a inline validation in a login from devise and The form don't recognice the data-taget. 

Here the view:

<div class="container" >
  <div class="row" >
    <div class="col-xs-12 col-sm-4 col-sm-offset-4 form-login" style="margin-top: 70px;" >
      <h2><i class="fas fa-bug"></i> Login <i class="fas fa-bug"></i></h2>

      <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name))  do |f| %>
        <div class="form-inputs" data-controller="login" data-action ="keypress->login#validateEmail">
          <%= f.input :email, data: { target: "login.content"} %>
          <%= f.input :password %>
          <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, "Log in" %>
        </div>
      <% end %>

      <%= render "devise/shared/links" %>

    </div>
  </div>
</div>

Here the controller:

import { Controller } from "stimulus"

export default class extends Controller {
  static targets = [ "content" ]

      validateEmail(){
        console.log( this.contentTarget );
    }
}

Here the error in the browser

application.js:106 Error invoking action "keypress->login#validateEmail"

Error: Missing target element "login.content"
    at Controller.get (target_properties.js:15)
    at Controller.validateEmail (login_controller.js:7)
    at Binding.invokeWithEvent (binding.js:52)
    at Binding.handleEvent (binding.js:29)
    at EventListener.handleEvent (event_listener.js:30)

{identifier: "login", controller: Controller, element: div.form-inputs, index: 0, event: KeyboardEvent}

thanks!

**Comment by javan** [comment]
Have you inspected your rendered HTML to see if it actually contains that target element (with the correct `data-target` annotation)?

**Comment by crojasu** [comment]
this is what it looks:
<input class="form-control string email optional" type="email" value="" name="user[email]" id="user_email" pb-role="username">
But, don't understand why is not containing the data-target

**Comment by crojasu** [comment]
this is what it looks:
`<input class="form-control string email optional" type="email" value="" name="user[email]" id="user_email" pb-role="username">`
But, don't understand why is not containing the data-target

**Comment by javan** [comment]
Hmm, try 
```ruby
<%= f.input :email, input_html: { data: { target: "login.content" } } %>
```
 or 
```ruby
<%= f.input :email, input_html: { "data-target" => "login.content" } %>
```
I'm just guessing based on the examples from https://github.com/plataformatec/simple_form. That's all I can do to help I'm afraid since your issue isn't with Stimulus.

**Comment by crojasu** [comment]
works!
thanks a lot @javan
