### ISSUE TITLE
How are actions attached to the same event executed ?

### ISSUE THREAD

**Issue by tdutreui** [stimulusjs/stimulus#229]
Hi everyone,

Given the following actions attached to the same event :
```
<div data-action="click->controller#actionOne click->controller#actionTwo click->controller#actionThree"/>
</div>
```

How are the different actions executed ? At the same time ? Do they wait for each other?

Thank you !
Thomas

**Comment by sstephenson** [comment]
Since version 1.1, Stimulus invokes actions in order from left to right, and an action can call `event.stopImmediatePropagation()` to prevent further actions from handling it.

See also: #149

**Comment by tdutreui** [comment]
Thank you :)

**Comment by nickclasener** [comment]
@sstephenson 
A followup question.
I'm using a [confirm alert from sweetalert](https://sweetalert2.github.io/)
The issue i'm having is that when the popup launches the following actions fire before cancel or confirm.
Thus using event.stopImmediatePropagation() solving the issue of premature firing.

But it raises the next issue i can't get the event to fire again when confirm is pressed. 

Is there a way to pause the event?
