### ISSUE TITLE
How turbolinks fit together with stimulus?

### ISSUE THREAD

**Issue by edwinyzh** [stimulusjs/stimulus#23]
Wonderful! The way stimulus works is so straight-forward and the concept is so easy to understand!

I'm really looking forward to the enhancement of the documents, for example, I still don't understand in which cases it needs turbolinks?

**Comment by georgeclaghorn** [comment]
You don’t need to use Turbolinks to use Stimulus. If you do use Turbolinks, Stimulus just works with no modification or configuration.
