### ISSUE TITLE
IE11 - Object doesn't support property or method `closest`

### ISSUE THREAD

**Issue by msxavi** [stimulusjs/stimulus#234]
Stimulus 1.1.1

Application is raising the error above from this line in Internet Explorer 11: https://github.com/stimulusjs/stimulus/blob/master/packages/%40stimulus/core/src/scope.ts#L36

**Comment by ngan** [comment]
https://stimulusjs.org/handbook/installing#browser-support

**Comment by javan** [comment]
Yeah, you need to include the `@stimulus/polyfills` package to support IE 11.
