### ISSUE TITLE
glitch stimulus starter is not working

### ISSUE THREAD

**Issue by Jarajesh** [stimulusjs/stimulus#235]
Hi , in the project page 
[https://stimulusjs.org/handbook/hello-stimulus](https://stimulusjs.org/handbook/hello-stimulus)
there is a link to Remix on Glitch https://glitch.com/edit/#!/import/github/stimulusjs/stimulus-starter I tried opening the link but was not able to see it working.

**Comment by javan** [comment]
I just tried that link and the project was imported as expected: https://glitch.com/~tremendous-seal. There isn't anything to *see* initially—just an empty controller for you to experiment with: https://glitch.com/edit/#!/tremendous-seal?path=src/controllers/hello_controller.js:3:0
