### ISSUE TITLE
"export as namespace" in index.d.ts

### ISSUE THREAD

**Issue by benjamin-hodgson** [stimulusjs/stimulus#238]
I want to use Stimulus as a UMD global from a **non-module-based** TypeScript project.

```typescript
// foo_controller.ts
class FooController extends Stimulus.Controller {
    // ...
}
```

The `index.d.ts` file which ships with Stimulus only declares a TypeScript module, not a UMD global as well, which means that you can't use Stimulus in a TS script file.

Please could you add [`export as namespace Stimulus`](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#support-for-umd-module-definitions) to `index.d.ts`?

**Comment by sstephenson** [comment]
We’d have to do this in a post-build step, I think. Our `.d.ts` files are generated by the TypeScript compiler, not checked into the source tree.

**Comment by benjamin-hodgson** [comment]
Is this not it? https://github.com/stimulusjs/stimulus/blob/master/packages/stimulus/index.d.ts

**Comment by sstephenson** [comment]
I’m sorry. I was thinking of the `@stimulus/core` package. You’re correct, that’s where the change should be made.

**Comment by benjamin-hodgson** [comment]
No worries. Would you like me to send you a pull request or would you prefer to do it yourself?

**Comment by sstephenson** [comment]
A pull request would be great - thank you!
