### ISSUE TITLE
Gem for asset pipeline

### ISSUE THREAD

**Issue by rainerborene** [stimulusjs/stimulus#24]
This is on the roadmap?

Just out of curiosity why did you decide to use TypeScript instead of CoffeeScript? Basecamp is moving towards TypeScript or something?

**Comment by javan** [comment]
No plans to release a gem. Stimulus is a plain ol' JavaScript library. You can add `stimulus.umd.js` to your sprockets bundle. Or, use [webpacker](https://github.com/rails/webpacker) to bundle the npm package. See the [Installation Guide](https://github.com/stimulusjs/stimulus/blob/master/INSTALLING.md#installation-guide) for more details.

> why did you decide to use TypeScript instead of CoffeeScript?

We like TypeScript's tooling and type checking for authoring libraries. That's all. :)
