### ISSUE TITLE
How to manually display the turbolinks loader bar in non-turbolinks ajax callbacks ?

### ISSUE THREAD

**Issue by jpic** [stimulusjs/stimulus#243]
Hi all!

Neat repo maintenance :+1:

So, I have a list page with a filter form that makes an ajax request and replaces part of the body every time the user changes a filter value.

Is it possible to trigger the turbolinks loader bar, as-if it was a normal turbolinks request ?

Thanks in advance

Keep up the great work :tophat:

**Comment by sigfrid** [comment]
I think a better place for such questions is https://discourse.stimulusjs.org/.

Have a good one.

**Comment by jpic** [comment]
Thanks for the heads up @sigfrid 

Have a great day
