### ISSUE TITLE
Allow webpack-helpers to have changeable postfix

### ISSUE THREAD

**Issue by KieranP** [stimulusjs/stimulus#244]
Currently, all files require "_controller" in the filename (https://github.com/stimulusjs/stimulus/blob/master/packages/%40stimulus/webpack-helpers/src/index.ts#L29). However, I'm looking to have a different folder for "components". e.g.

```
components/
  invoices_list_component.js
controllers/
  invoices_controller.js
```

Any chance this would be possible?

**Comment by javan** [comment]
We don't plan to support that, but you're free to copy our webpack helpers into your application and modify them to your liking.
