### ISSUE TITLE
Jest + Stimulus - data-target issues

### ISSUE THREAD

**Issue by J6K** [stimulusjs/stimulus#246]
Following a guide I found in one of the issues here: https://shime.sh/testing-stimulus

And for whatever reason, I run into an error stating that `element.closest` is not a function.

```javascript
import { Application, Controller } from "stimulus";

class Submit extends Controller {
  static targets = [ 'submit' ]

  connect() {
    this.enableIfValid()
  }

  enableIfValid = () => {
    const { submitTarget } = this // this line causes the error
  }
}

describe("SubmitController", () => {
  describe("#enableIfValid", () => {
    beforeEach(() => {
      document.body.innerHTML = `<div data-controller="submit">
        <button id="button" data-action="submit#enableIfValid" data-target="submit.submit" />
      </div>`;

      const application = Application.start();
      application.register("submit", Submit);
    });

    it("copies input and sets it on output", () => {
      const button = document.getElementById("button");
    });
  });
});
```

**Comment by J6K** [comment]
`node_modules/stimulus/dist/stimulus.umd.js:1254`

I've logged `element` and confirmed it is a `HTMLButtonElement` and that it is an instance of Element but `element.closest` is still undefined

**Comment by javan** [comment]
I believe your issues is with jsdom (used by Jest), which may or may not support `Element.closest()` depending on the version:

- https://github.com/jsdom/jsdom/issues/1555
- https://github.com/jsdom/jsdom/pull/1951

Adding the [@stimulus/polyfills](https://www.npmjs.com/package/@stimulus/polyfills) package to your bundle may help.
