### ISSUE TITLE
making "oninput" the default event for inputs/textareas instead of "onchange"?

### ISSUE THREAD

**Issue by localhostdotdev** [stimulusjs/stimulus#248]
I know this is a breaking change but it would more closely reflect what I think most people want when listening to changes on an input.

MDN doc for oninput: https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/oninput

MDN doc for onchange: https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onchange

real world examples:

- search autocomplete: oninput
- live search: oninput
- live preview: oninput
- validations: oninput/onchange/onsubmit (but I would expect oninput here personally and then the validation needs to be smart about not erroring too early)
- textarea's custom handlers: oninput

onchange to me would be kind of the "old way" of doing things when users need to submit a form before seeing a result.

react even calls it "onChange" but it's really "onInput": https://codepen.io/anon/pen/pmzjQV?editors=0010

**Comment by javan** [comment]
Great suggestion!

**Comment by jellymann** [comment]
This breaks inputs of type checkbox and radio, since they do no fire an `input` event ever, and should still be on `change`

**Comment by KevinBerthier** [comment]
For anyone encountering the issue, this breaks file inputs on Safari 12
