### ISSUE TITLE
404 error for https://stimulusjs.org/reference/controllers/ page

### ISSUE THREAD

**Issue by ZmagoD** [stimulusjs/stimulus#250]
Hi
I don't know if this is the right place to report this but there is a 404 error for references page 

![Screenshot 2019-05-16 at 20 10 32](https://user-images.githubusercontent.com/7046787/57877016-0da4dd00-7817-11e9-9eb3-83b8b41ddb94.png)

**Comment by sstephenson** [comment]
GitHub seems to have made a configuration change that broke all of our URLs. I’ve contacted support; it looks like [we’re not alone](https://twitter.com/search?f=tweets&vertical=default&q=github%20pages&src=typd).

In the meantime, you can access the documentation at https://stimulusjs.now.sh/ or view the Markdown source at https://github.com/stimulusjs/stimulus/tree/master/docs.

**Comment by sstephenson** [comment]
Those links are working again:
https://twitter.com/githubstatus/status/1129104279380398080

Thanks for letting us know!

**Comment by ZmagoD** [comment]
Great thank you @sstephenson
