### ISSUE TITLE
Uncaught Error: Module build failed from from ./node_modules/rails-erb-loader/index.js

### ISSUE THREAD

**Issue by SylarRuby** [stimulusjs/stimulus#258]
`"stimulus": "^1.1.1"`
`rails 6 rc1`
`webpack "^4.29.6"`

Hi all. This would be my first to use Stimulus in a production environment. In development, all is well. When I ran both:

* `RAILS_ENV=production rake assets:precompile`
* `NODE_ENV=production bundle exec rake webpacker:compile`

My stimulus js controllers fail and points to, for example, line 2 (without the 👈🏼):

```js
export default class extends Controller {
  static targets = [ "file", "image" ] 👈🏼
  [...]
}
```

Inside config/webpack/loaders/erb.js 

```js
module.exports = {
  test: /\.erb$/,
  enforce: 'pre',
  exclude: /node_modules/,
  use: [{
    loader: 'rails-erb-loader',
    options: {
      runner: (/^win/.test(process.platform) ? 'ruby ' : '') + 'bin/rails runner'
    }
  }]
}
```

A quick google search said something about comments in js file? My `javascript/controllers` only has one `.js.erb` file, others are `.js`

Do I need to run a special command for production? Thanks.

**Comment by javan** [comment]
You're probably missing the [`@babel/plugin-proposal-class-properties`](https://babeljs.io/docs/en/babel-plugin-proposal-class-properties) plugin (see https://stimulusjs.org/handbook/installing#using-babel). If that's not it, feel free to repost this question in our [community forum](https://discourse.stimulusjs.org/).
