### ISSUE TITLE
Add JSDoc to methods

### ISSUE THREAD

**Issue by fleck** [stimulusjs/stimulus#259]
Would you consider adding JSDoc comments to methods? For example in @stimulus/core/dist/src/controller.d.ts:

```
    /**
     * Invoked by Stimulus anytime the controller is connected to the DOM
     * https://stimulusjs.org/reference/lifecycle-callbacks#methods
     */
    connect(): void;
```

would yield:
![image](https://user-images.githubusercontent.com/1706321/59971329-f6f55280-9547-11e9-8247-5c80ec8084e7.png)

Having inline documentation in addition to the signature is really nice!

**Comment by fleck** [comment]
This actually applies to any part of the code, not just methods:

![image](https://user-images.githubusercontent.com/1706321/59971358-99add100-9548-11e9-8f02-ded7c5a7f909.png)

Also nice having links to docs right there in the editor and being able to skip the stop of googling...

**Comment by sstephenson** [comment]
Yes! We hope to get to this in a future release.
