### ISSUE TITLE
Add testing in the docs

### ISSUE THREAD

**Issue by guledali** [stimulusjs/stimulus#260]
https://stimulusjs.org/handbook/ Please add information regarding testing in the handbook.

**Comment by guledali** [comment]
Im going to close this one, they mention in a different issue https://github.com/stimulusjs/stimulus/issues/34 That testing is done with Capybara and selenium here is a link https://guides.rubyonrails.org/testing.html#system-testing

If you are not using rails then https://www.cypress.io/ might be a good option to tests these.

**Comment by nogtini** [comment]
I think a brief mention at least somewhere in the Stimulus handbook addressing that it's preferred to use system tests (and no current path for unit tests) would bode well for transparency. Even just a brief mention in something like **testing support** after [**browser support**](https://stimulusjs.org/handbook/installing#browser-support) would be helpful.

**Comment by SampsonCrowley** [comment]
This is terrible for library authors. System tests are the end goal, but unit tests also have their place in making sure individual extensions work properly.

Especially now that the `bless` function is gone, it is near impossible to efficiently test simple feature additions are working properly through jest unit tests.

not everyone needs full system tests for everythign
