### ISSUE TITLE
Chrome developer tool!

### ISSUE THREAD

**Issue by guledali** [stimulusjs/stimulus#265]
Please develop a chrome plugin to keep track of all `getters` and the `setters` in the page. This would improve the developer experience for newcomers. 

I mean it almost impossible right now to know if you have changed the state or not. On top of that you still have update the dom to reflect the state that you got. I don't like code-guessing at all in this case having some plugin to keep track of all changes would ease development.

**Comment by javan** [comment]
Thanks for the suggestion! Feel free to start a thread on https://discourse.stimulusjs.org/ to continue the discussion.
