### ISSUE TITLE
Controller only working for a link and not a button. why? 

### ISSUE THREAD

**Issue by philip-keep** [stimulusjs/stimulus#269]
Hello,

I am unable to get this  action: "ajax:beforeSend->delete#click to work on a button but it works on a link. The action is to delete a comment. The following buttons and links have identical attributes. The Rails form helper naturally generates different html for the button and the link, but the button should the used in this circumstance. The delete is an action, it doesn't take the user somewhere so a link isn't appropriate. But it isn't working as a button. 
Am I doing something incorrectly on the button? How can I make it work with a button, or does it not work with buttons? 
Thanks. 

   <%= button_to  comment_path(comment), 
              method: :delete, 
              remote: true,             
              data:  {  target: "delete.link",  action: "ajax:beforeSend->delete#click"} do %>
                      delete button
              <% end %>

              <%= link_to "delete link", comment_path(comment), 
              method: :delete, 
              remote: true,            
              data: { target: "delete.link", action: "ajax:beforeSend->delete#click" } %>

                <%= button_to "delete button, comment_path(comment), 
              method: :delete, 
              remote: true,           
              data: { target: "delete.link", action: "ajax:beforeSend->delete#click" } %>

**Comment by philip-keep** [comment]
Hi Tyler,

I appreciate you taking an interest this issue, thank you.

The aside that you mentioned isn't the issue, in the real code I'm using
translations but I removed them from the pasted code in order to remove the
irrelevant, the missing quote mark was my typo, i edited when posting and
not in the code, itself.

I see what you mean about overloading the term action. To provide some
context, the delete button appears on a user comment. The user can delete
and edit their own comments. So the delete button is an interaction
available to the user. The actual Stimulus action is the click method.

Your summary of

   - You are listening for the DOM event ajax:beforeSend
   - The controller identifier here is delete
   - The method in the delete_controller you are trying to invoke is click

is all correct.
The controller has a console.log in the connect method. That logs on page
load.
The click method currently has a console.log as the first line. This is
only logs when the link is clicked.
The method contains  event.preventDefault();  I can post the full method if
required but as it isn't logging on the first line the details of the
method don't seem to matter.

Here's the html that is produced when I removed one of the buttons, so now
there is only one a button and a link, both defined with the same
attributes in Rails.

<div class="review__buttons" role="group" data-controller="delete"
aria-label="Edit/delete your review">

                <button class="review__edit-button button-as-link
button-as-link--link-color" data-js="review-item-edit"
data-target="editButton" data-action="review#showEditForm" id="283"
type="button">
                    Edit
                </button>
              <form class="button_to" method="post"
action="/en/book/2/comments/283" data-remote="true"><input type="hidden"
name="_method" value="delete"><button class="review__delete-button
button-as-link button-as-link--link-color" data-target="delete.link"
data-action="ajax:beforeSend->delete#click"
type="submit">Delete</button><input type="hidden" name="authenticity_token"
value="KjWVn4Gl2PIl7FaDyU+r2X7Z7DOFYSlVc1zzCwJ+4NZKKF8/rJBWUifAljL7wmGXTvKfEeGJS2wF7VTVQ1preA=="></form>


              <a class="review__delete-button button-as-link
button-as-link--link-color" data-target="delete.link"
data-action="ajax:beforeSend->delete#click" data-remote="true"
rel="nofollow" data-method="delete" href="/en/book/2/comments/283">delete
link</a>

        </div>

So I guess that it's do with the button_to automatically adding a form for
the button. Elsewhere I have used a form containing a button successfully
with Stimulus ajax events. But the difference there is that I have applied
the ajax data-action, directly to the form e.g.
<%= form_with(model: comment,
data:{
js:'comment-form-add',
target: 'review.addForm',
action: 'ajax:success->review#postCommentSuccess' ,
type: "html"
} ,
id: "comment-form-add",
class: "hidden") do |form| %>

In that form I'm using a manually created button.
So I guess that the way is to manually create a button. I'll try it now.
Yes it worked when I manually added the button instead of using Rails the
button_to helper.


<button class="review__delete-button button-as-link
button-as-link--link-color"
data-target="delete.link"
data-action="ajax:beforeSend->delete#click"
data-remote="true"
rel="nofollow"
data-method="delete"
href="<%= comment_path(comment) %>">delete link</button>

So it seems like manually creating buttons is the best way when working
with Rails and Stimulus. Maybe always or maybe only when Ajax events are
involved.

I had a look at the button_to page
https://apidock.com/rails/ActionView/Helpers/UrlHelper/button_to
to see if the form creation can be disabled but it says that it does it to
prevent bots from submitting forms. It may be possible via the
html_options.

Thanks for your help, your requests for more information make me look at
this again.

Best Regards,
Phil.

**Comment by airblade** [comment]
> It may be possible via the html_options.

It is :)

This was your original:

```ruby
<%= button_to "delete button, comment_path(comment), 
          method: :delete, 
          remote: true,           
          data: { target: "delete.link", action: "ajax:beforeSend->delete#click" } %>
```

It puts the data attributes on the button element, not the form.

Change it to this:

```ruby
<%= button_to "delete button, comment_path(comment), 
          method: :delete, 
          remote: true,           
          form: {data: { target: "delete.link", action: "ajax:beforeSend->delete#click" }} %>
```

This puts the data attributes on the form element.
