### ISSUE TITLE
Include `*.ts` source files for resolving sourcemaps

### ISSUE THREAD

**Issue by charlesbjohnson** [stimulusjs/stimulus#275]
Hi there 👋,

I noticed that this package [includes sourcemaps](https://github.com/stimulusjs/stimulus/blob/a82a8a5dddcc0a15089f269fc4be8a8c36b17b97/packages/tsconfig.build.json#L9), but the mapped files are not actually included in the `npm` package. Would you consider removing `src` from `.npmignore` so that the sourcemaps will work?

If you look at [`@stimulus/core/dist/index.js`](https://unpkg.com/browse/@stimulus/core@1.1.1/dist/index.js), for example, the `sourceMappingURL` decodes to...

```jsc
{ "file":"index.js", "sources":["../index.ts"] }
```

But none of the `*.ts` files are actually included in the package.

**Comment by rik** [comment]
The absence of the mapped files adds lots of warnings to the logs of builds using Parcel.
```
⚠️  Could not load source file "../index.ts" in source map of "../node_modules/@stimulus/core/dist/index.js".
```
