### ISSUE TITLE
Stimulus doesn't remove listeners automatically after disconnecting

### ISSUE THREAD

**Issue by ricglz0201** [stimulusjs/stimulus#276]
Hello,
I don't know if this is the expected behavior but any of my listeners are being removed automatically when the controller is disconnected. I have to do it myself.
This is the code of my current controller.
```javascript
export default class extends Controller {
  connect() {
    ...
    $(document).on('nested:fieldAdded', function(event) {
      console.log('hello there');
      ...
    });
  }
}
```
This controller is my main controller, so it's used in a lot of my pages, when I go to 2 or more pages with this controller each listener is stack. Making that if I trigger the `nested:fieldAdded` event, the log is print twice. I don't know if this is not normal or if it's expected that I clean my listeners myself. Thank you.

**Comment by adrienpoly** [comment]
Stimulus will automatically create event listeners for the actions you define `data-action` and tear them down for you.

Here you are manually connecting a jQuery listener. 
It is your responsibility to teardown this event in the `disconnect` function. 
Stimulus has no knowledge about it.

**Comment by javan** [comment]
That's correct. [Actions](https://stimulusjs.org/reference/actions) are the conventional way to handle events, and Stimulus automatically adds and removes listeners for them.
