### ISSUE TITLE
On Change event

### ISSUE THREAD

**Issue by savroff** [stimulusjs/stimulus#28]
Right now when you want to fire an action on `change->` 
The event will be fired only when u change focus from input field itself.
```
<inpit type="text" data-action="change->controller#change_value" />
```
Should it work like that? 
I thought it should fire an action on every input value change.

**Comment by georgeclaghorn** [comment]
Browsers only dispatch the [`change`](https://developer.mozilla.org/en-US/docs/Web/Events/change) event when a change is committed (e.g. when a text input is blurred):

> The change event is fired for `<input>`, `<select>`, and `<textarea>` elements when a change to the element's value is committed by the user. **Unlike the `input` event, the `change` event is not necessarily fired for each change to an element's value.**

**Comment by savroff** [comment]
Got it. Thank you! @georgeclaghorn

**Comment by kami-zh** [comment]
> I thought it should fire an action on every input value change.

I think you can do it using the `keypress` event 👍

**Comment by xhafan** [comment]
> I think you can do it using the `keypress` event +1

`keypress` does not work for backspace in Firefox for me. I use `keyup` event.

**Comment by octavio275** [comment]
Algun ejemplo de select anidados relacionados en stimulus con change?
