### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Aquaj** [stimulusjs/stimulus#282]
Hi,

I've been working with stimulus on a project and having the bug described in #222 (controllers don't react to events raised during `connect()`). I've seen that it's been fixed in 6129975c2ab98b01e months ago, so for now I've been using the repo's version locally, but I can't exactly deploy that.

I was hoping we might get a release including the latest developments. Or are we waiting on something specific before the next one ? (Maybe #202 ?)

**Comment by adrienpoly** [comment]
Hey 👋@Aquaj

They are undocumented dev builds generated here : https://github.com/stimulusjs/dev-builds/releases

The latest build from September 18th is from `master` and includes your patch

While waiting for an official release you can maybe put this in your `package.json`:

```
"stimulus": "https://github.com/stimulusjs/dev-builds/archive/50ad06a/stimulus.tar.gz"
```

**Comment by Aquaj** [comment]
Hey there Adrien !

Will do that then in the meantime (my current setup involves `yarn link`, but that's not very deployable.
Thanks for the tip ! 👍
