### ISSUE TITLE
Refresh server generated form over AJAX

### ISSUE THREAD

**Issue by gamade** [stimulusjs/stimulus#286]
Hello,

I have a form, which can change with the input. A short example: A reservation is to be created. To do this, the user fills out the business event (for example, using select). Now the selected event must be sent to the server, so that the server determines the possible categories and offers them for selection. Now the category is selected, which determines the maximum bookable tickets and the price per ticket. Finally, the number of tickets is selected and the price is calculated. With Save the form is sent to the server. 

I use Rails 6 with stimulus for simple dynamic form modifications (e.g. add or delete embedded fields). Now I have to call the controller#new method again and again with the updated fields so that it can get the necessary data.

I perfer to compose the form server-side to have a single point of logic and/or validation. 

Is there an example for this? I currently can't get it to work. Or is there a better way to do something like this?

Thank you for your help

Best regards
Markus

**Comment by javan** [comment]
Our community forum, https://discourse.stimulusjs.org, is the best place for questions like this. You're more likely to get an answer there too. So, please re-post it there. ✌️
