### ISSUE TITLE
[Question] How much do you use it in Basecamp?

### ISSUE THREAD

**Issue by heloameneses** [stimulusjs/stimulus#288]
Hi!

I'm curious to know how much you use it in Basecamp. If it's fine to share it, of course.
In which cases have you decided not to use it and what did you look for instead?

**Comment by javan** [comment]
We use it… a lot? Feel free to [*View Source*](https://m.signalvnoise.com/paying-tribute-to-the-web-with-view-source/).  :)

![Screen Shot 2020-02-19 at 12 59 48 PM](https://user-images.githubusercontent.com/5355/74876434-83932300-5318-11ea-80d8-1ec4375c97cf.png)
