### ISSUE TITLE
Broken nested scopes

### ISSUE THREAD

**Issue by berndartmueller** [stimulusjs/stimulus#289]
Hello!

I noticed when nesting multiple controllers with the same identifier, targets are not working properly. I already found the issue in code. It used to work but after following commit, it stopped doing so:

[https://github.com/stimulusjs/stimulus/commit/40366c8a0387e5035cb1202a6d223dba07483b55#diff
-8298064eeca3367b90aa4edcecf7999a](url)

It happens within `containsElement(...)` because `element.closest()` returns the same element in case the controller selector is exactly the same (which is the case when nesting controllers with the same identifier). 

A possible fix could be using the parent Element if available: 
```
containsElement = (element: Element): boolean => {
    let baseElement = element;

    if (element.parentElement) {
      baseElement = element.parentElement;
    }

    return baseElement.closest(this.controllerSelector) === this.element
  }
```

But 1 test fails and I can not really spot the issue. Can anyone please help me out? 

Thanks a lot!

**Comment by javan** [comment]
> I noticed when nesting multiple controllers with the same identifier, targets are not working properly.

Can you share your failing test case? We can't help without seeing example markup, at least.

**Comment by berndartmueller** [comment]
Sure @javan 

It fails with following error:

`HeadlessChrome 80.0.3987 (Mac OS X 10.15.3) ActionTests nested actions FAILED
	Expected: 1
	Actual: 3
	    at ActionTests.LogControllerTestCase.assertActions (webpack:///./packages/@stimulus/core/dist/tests/log_controller_test_case.js?:82:21)
	    at ActionTests.eval (webpack:///./packages/@stimulus/core/dist/tests/cases/action_tests.js?:114:30)
	    at step (webpack:///./packages/@stimulus/core/dist/tests/cases/action_tests.js?:46:23)
	    at Object.eval [as next] (webpack:///./packages/@stimulus/core/dist/tests/cases/action_tests.js?:27:53)
	    at fulfilled (webpack:///./packages/@stimulus/core/dist/tests/cases/action_tests.js?:18:58)`

I don't fully understand yet how those tests are structured and I would have to dig deeper.

**Comment by javan** [comment]
That failure is with your `containsElement()` "possible fix" above, right? I'm trying to understand what problem you're trying to fix in the first place. 

Can you share a snippet of HTML that illustrates "nesting multiple controllers with the same identifier" and explain what you mean by "targets are not working properly"?

**Comment by berndartmueller** [comment]
I have an example as following:
```
<div data-controller="test">
    <div data-controller="test" data-target="test.children"></div>
    <div data-controller="test" data-target="test.children"></div>
</div>
```

Maybe I'm mistaking something and my thinking is plain wrong. As seen in the example markup, I would like to assign child controllers of the same type (identifier) to a single parent controller. But `childrenTargets` is undefined/empty because when looping over those child controllers, `containsElement()` returns the same element and not as supposed the parent controller element (caused by having the same controller selector).

I fixed it for now by changing the html a little bit:
```
<div data-controller="test">
    <div data-controller="test-child" data-target="test.children"></div>
    <div data-controller="test-child" data-target="test.children"></div>
</div>
```
I simply registered a new controller: 
```
application.register('test', TestController);
application.register('test-child', TestController);
```

Maybe that's the way to go anyway 😄

**Comment by javan** [comment]
Each `data-controller` attribute creates a new scope around that element, including the element itself, so it's working as expected. I totally see why you got tripped up though and appreciate that you took the time to investigate!

> It used to work but after following commit, it stopped doing so: https://github.com/stimulusjs/stimulus/commit/40366c8a0387e5035cb1202a6d223dba07483b55

FWIW, I tested your scenario before and after that commit and the behavior was the same. I don't think anything changed there.
