### ISSUE TITLE
Getting a warning on hello_controller.js

### ISSUE THREAD

**Issue by rept** [stimulusjs/stimulus#290]
I installed Stimulus with this command:

    bundle exec rails webpacker:install:stimulus

This installed without any issues, created a controller folder and added the hello_controller.js file.

When running bin/webpack-dev-server I get the following message:

```
WARNING in ./app/javascript/controllers/hello_controller.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/stijn/projects/nobi/app/javascript/controllers/hello_controller.js: Support for the experimental syntax 'classProperties' isn't currently enabled (13:18):
```

What is causing this, and is this something to worry about?

I have Webpacker version 4.2.2, Rails 5.2.1 and Ruby 2.6.5

**Comment by rept** [comment]
Adding this loader solves it.  But I wonder if this should be documented somewhere?  That you need to add Babel and this loader for it to work out of the box.

```
module.exports = {
    test: /\.js(\.erb)?$/,
    exclude: /node_modules/,
    loader: 'babel-loader',
    options: {
        plugins: [
            require('@babel/plugin-proposal-class-properties'),
        ]
    }
}
```

**Comment by javan** [comment]
> I wonder if this should be documented somewhere?

Somewhere like [right here](https://stimulusjs.org/handbook/installing#using-babel
)? :)

> #### Using Babel
> If you're using [Babel](https://babeljs.io/) with your build system, you'll need to install the [@babel/plugin-proposal-class-properties](https://babeljs.io/docs/en/babel-plugin-proposal-class-properties) and add it to your configuration:
>
> ```js
>  // .babelrc
>  {
>    "presets": ["@babel/preset-env"],
>    "plugins": ["@babel/plugin-proposal-class-properties"]
>  }
> ```

Webpacker includes that Babel plugin automatically, I think. It's [a dependency](https://github.com/rails/webpacker/blob/cb4e4c8c137780ffa549c71b84e66b3ec8c98575/package.json#L16), at least. I'd try creating a fresh Rails app with webpacker + (`rails webpacker:install:stimulus`) and see if the same problem occurs. If it does, consider opening an issue there.
