### ISSUE TITLE
Static application start not async

### ISSUE THREAD

**Issue by khebbie** [stimulusjs/stimulus#294]
On this line:
https://github.com/stimulusjs/stimulus/blob/master/packages/@stimulus/core/src/application.ts#L16
The async version of Application.start is called, but the function itself is not async.
This means that the function will probably return before the result is ready.
Using this in a test I got some errors due to the async nature of the code.

Is there some good reason why this method is not marked `async`

**Comment by javan** [comment]
> This means that the function will probably return before the result is ready

The returned `application` instance should be ready (to register controllers, for example) even it hasn't `start()`ed yet.

> Using this in a test I got some errors due to the async nature of the code

Can you share an example?

**Comment by khebbie** [comment]
If I do like so in a test:
```
            application = Application.start();
            application.register("displayBanner", DisplayBannerController);
```
Then I cannot be sure the application has been started yet, since the static version of `start()` is not async and it is calling the async version of `start()`

There is a simple solution to this:
```
            const application = new Application()
            await application.start()
```
This works since I am now able to wait on the `start()` function to finish

**Comment by javan** [comment]
> This works since I am now able to wait on the `start()` function to finish

👌
