### ISSUE TITLE
Action order not firing in correct order per documentation

### ISSUE THREAD

**Issue by phedinkus** [stimulusjs/stimulus#295]
I'm having a similar problem as listed in [this issue](https://github.com/stimulusjs/stimulus/issues/255). 

I have two controllers with two actions associated on a button click. Generally the structure looks like this: 
```html
<div data-controller="location-map">
  <button 
    data-controller="button-active" 
    data-action="button-active#toggle location-map#select">
    click me
  </button>
</div>
``` 

When I click the button I see a console log from the `location-map#select` function then the `button-active#toggle` function. Based on what the documentation says for action firing ("from left to right") I would expect the opposite. 

I'm on version 1.1.1

**Comment by javan** [comment]
Can you share a working example that reproduces the issue? I tried https://codepen.io/javan/pen/xxGWWjo?editors=1011 and am seeing the correct left-to-right order.

![Screen Shot 2020-03-13 at 11 21 05 AM](https://user-images.githubusercontent.com/5355/76649041-19d3f680-651d-11ea-8480-d9ab1189f064.png)

**Comment by javan** [comment]
Going to close this for now. Happy to reopen if you can share a reproducible example.

**Comment by ankalus** [comment]
Hi, I have a similar issue.
When I have many actions where some of them have a declared event, the order of actions execution is invalid (not "from left to right").

Example:
```js
export default class extends Controller {
  test1() { console.log("test1") }
  test2() { console.log("test2") }
}
```
Correct order of execution: test1, test2
  ```html
<div data-controller="test">
  <input data-action="test#test1 test#test2" type="checkbox">
</div>
```

Incorrect order of execution: test2, test1
```html
<div data-controller="test">
  <input data-action="change->test#test1 test#test2" type="checkbox">
</div>
```
I'm on version 3.0.1.

**Comment by rik** [comment]
The [default event type](https://stimulus.hotwired.dev/reference/actions) Stimulus uses for `<input>` is `input`. So your example is equivalent to:
```html
<div data-controller="test">
  <input data-action="change->test#test1 input->test#test2" type="checkbox">
</div>
```

And the `input` event is dispatched before the `change` event. That is the normal behaviour of DOM events.
