### ISSUE TITLE
use dynamic imports instead of require.context

### ISSUE THREAD

**Issue by fleck** [stimulusjs/stimulus#298]
Would you be open to a PR that would allow this API (or something similar)?:

```js
import { startApplication } from "stimulus";

startApplication(controllerName => import(`./${controllerName}_controller`));
```

the implementation would look something like this:
```ts
import { Application } from "stimulus";

export const startApplication = (
  controllerImportFunction: (controllerName: string) => Promise<any>
) => {
  const application = Application.start();

  const registeredControllers = new Set();

  const registerControllers = async (element: Element | Document) => {
    element.querySelectorAll("[data-controller]").forEach(async c => {
      const controllerName = c.getAttribute("data-controller");

      if (!controllerName || registeredControllers.has(controllerName)) return;

      registeredControllers.add(controllerName);

      const { default: controller } = await controllerImportFunction(
        controllerName
      );

      application.register(controllerName, controller);
    });
  };

  new MutationObserver(function callback(mutationList) {
    mutationList.forEach(function ({ target }) {
      if (target instanceof Element) {
        registerControllers(target);
      }
    });
  }).observe(document, {
    childList: true,
    subtree: true
  });

  registerControllers(document);

  return application;
};
```
This method of loading controllers can reduce initial JS payloads significantly for large applications that have a lot of JS specific to certain areas/users/features. Another small benefit is that this uses the standardized import syntax instead of the webpack specific require.context.

BTW, thanks for Stimulus! I've dabbled with it in the past, but started using it heavily a couple of weeks ago and it's very nice, really brings fresh life into 'old school' server rendered HTML

**Comment by rik** [comment]
I've discovered https://github.com/danieldiekmeier/stimulus-controller-resolver via https://discourse.stimulusjs.org/t/stimulus-with-dynamic-import-and-webpack/966/3.

**Comment by fleck** [comment]
Since this functionality is easy enough to setup using the above plugin or rolling something yourself I'm going to close this.
