### ISSUE TITLE
jQuery / build question

### ISSUE THREAD

**Issue by seanfcarroll** [stimulusjs/stimulus#309]
StimulusJS is an incredible "framework", I've been using it extensively in Rails projects for several years now as a drop-in replacement for jQuery and a way to avoid going with React or VueJS except when absolutely needed.

In a [recent dependabot PR](https://github.com/stimulusjs/stimulus/pull/304), it was highlighted that Stimulus includes jQuery, which was surprising. You can see it [yarn.lock](https://github.com/stimulusjs/stimulus/blob/master/yarn.lock#L7629-L7637) and [here](https://github.com/stimulusjs/stimulus/blob/master/yarn.lock#L4719-L4722).

Upon further investigation, it can be seen that jQuery is included by [Typedoc](https://typedoc.org/) which is [listed as a dependency](https://github.com/stimulusjs/stimulus/blob/master/package.json#L38). Assuming Typedoc is needed to generate the StimulusJS documentation site, has it been excluded from the build? 

The StimulusJS bundle size [is apparently 6.45k](https://bestofjs.org/projects/stimulus), which is awesome. 

Does that mean jQuery has been shaken out of the final build? How is this done?

**Comment by adrienpoly** [comment]
The runtime build of Stimulus has no dependency to third party libraries. 

https://npm.anvaka.com/#/view/2d/stimulus

To my knowledge jQuery is only used for docs as you pointed out

**Comment by seanfcarroll** [comment]
Thanks @adrienpoly
