### ISSUE TITLE
Custom elements interoperability?

### ISSUE THREAD

**Issue by 007lva** [stimulusjs/stimulus#31]
stimulus seems very unobtrusive so I think it could work well with Custom elements, isn't? Would be great to see it on https://custom-elements-everywhere.com/

**Comment by javan** [comment]
Stimulus should work perfectly along side custom elements. We use both in Basecamp. I don't think we'll put any effort towards a test suite for https://github.com/webcomponents/custom-elements-everywhere, but feel free to!

**Comment by 007lva** [comment]
Thanks!
