### ISSUE TITLE
Build-step

### ISSUE THREAD

**Issue by Lewiscowles1986** [stimulusjs/stimulus#317]
Is there a way to use the data-attributes only for development, and crystallize behavior through a build-step?

I worked with Stimulus a fair bit in my last role and it's indeed a powerful and expressive syntax, but once I have my components finished, it would be really nice to be able to move all the `data-xyz` into some form of configuration block; so that I can reduce DOM noise.

**Comment by javan** [comment]
There is not. It's an interesting idea, but too ambitious for _**A modest JavaScript framework for the HTML you already have**_, IMO.
