### ISSUE TITLE
Documentation does not clearly indicate that "data-controller" should include minuses, even if the controller file is underscored

### ISSUE THREAD

**Issue by wmakley** [stimulusjs/stimulus#320]
Hi, just a small request as a new adopter! Something that tripped me up for way too long on my first small project to try stimulus. If you have the following controller:

`controllers/my_controller.js`

And the following markup:

`<div data-controller="my_controller">`

It will not work, and there won't be an error message indicating "controller not found" or similar. It needs to be:

`<div data-controller="my-controller">`

I feel like this is just kind of surprising, as had to read through quite a lot of the introductory before I found an example proving what my problem was.

**Comment by tleish** [comment]
@wmakley - [See Controllers > Naming Conventions](https://stimulusjs.org/reference/controllers#naming-conventions)
