### ISSUE TITLE
Provide type declarations

### ISSUE THREAD

**Issue by panoply** [stimulusjs/stimulus#322]
Really need typings. Painful when using with vscode.  Thanks.

**Comment by javan** [comment]
Stimulus is written in TypeScript and all of its packages include `.d.ts` files ([example](https://unpkg.com/browse/@stimulus/core@1.1.1/dist/src/)). Perhaps something's up with your editor?

**Comment by panoply** [comment]
Ushh! my mistake, I had an error within my `jsconfig.json` apologies!
