### ISSUE TITLE
Npm registry availability issues

### ISSUE THREAD

**Issue by freiden** [stimulusjs/stimulus#323]
Hi, it seems like the last versions of the javascript project maintained by the Basecamp team are unavailable on npm registry including Stimulus:

>     npm ERR! code E404
>     npm ERR! 404 Not Found - GET https://registry.npmjs.org/@stimulus/polyfills/-/polyfills-1.1.1.tgz
>     npm ERR! 404
>     npm ERR! 404  '@stimulus/polyfills@latest' is not in the npm registry.
>     npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
>     npm ERR! 404
>     npm ERR! 404 Note that you can also install from a
>     npm ERR! 404 tarball, folder, http url, or git url.
>     npm ERR! A complete log of this run can be found in...

Can you help fixing the issue?

**Comment by tom-stone-yudu** [comment]
I'm getting the same thing attempting to installing stimulus via yarn (verbose included):

`
[1/4] 🔍  Resolving packages...
verbose 0.852047453 Performing "GET" request to "https://registry.yarnpkg.com/stimulus".
verbose 0.983139872 Request "https://registry.yarnpkg.com/stimulus" finished with status code 200.
verbose 0.987171036 Performing "GET" request to "https://registry.yarnpkg.com/@stimulus%2fcore".
verbose 0.988216785 Performing "GET" request to "https://registry.yarnpkg.com/@stimulus%2fwebpack-helpers".
verbose 1.030328554 Request "https://registry.yarnpkg.com/@stimulus%2fcore" finished with status code 404.
verbose 1.044781645 Error: Couldn't find package "@stimulus/core@^1.1.1" required by "stimulus" on the "npm" registry.
`

**Comment by adrienpoly** [comment]
I think there is an issue with npm right now. I am having similar errors with other packages

**Comment by javan** [comment]
https://status.npmjs.org/incidents/cksjqc1w11v5

**Comment by freiden** [comment]
Thanks @adrienpoly
