### ISSUE TITLE
Object Attributes

### ISSUE THREAD

**Issue by cpanderson** [stimulusjs/stimulus#326]
I was looking for a way to easily pass all of an object's attributes to the controller instead of having to specify each attribute separately. When I did this...

`<div data-controller="my-controller" data-my-controller-attributes="<%= @user.attributes %>"></div>`

To my surprise I got (example)...

`<div data-controller="my-controller" data-my-controller-attributes-id="1" data-my-controller-attributes-name="Bob" data-my-controller-attributes-email="bob@email.com" ...`

Is this documented anywhere? It's great but does throw a lot of stuff on the page which I was trying to avoid but glad it did it for me automatically. Is there a better way?

Also, probably very risky security wise.

**Comment by javan** [comment]
Can you share an example of your controller code or minimal steps to reproduce?
