### ISSUE TITLE
Add load listener

### ISSUE THREAD

**Issue by teekenl** [stimulusjs/stimulus#327]
Hey guys how can i add eventlistener in stimulus way something like this

```js
var div = document.getElementsByTagName("div")[0];
// does not work (console is not written to when page loads)...
div.addEventListener("load", function(){console.log("div load event")}, false);
```

**Comment by teekenl** [comment]
Also i think documentation is not well written in my opinion, some of custom action listener not being fully listed i have to go thorugh the codebase to find out what are the available option. it is frustrating for a user.

**Comment by robzolkos** [comment]
Hi @teekenl  - can you elaborate on what you are trying to do?  Perhaps more code.   Are you doing this in the controller `connect` method (which runs when the dom is connected to the stimulus controller) ?

**Comment by teekenl** [comment]
I was trying to achieve to trigger controller action automatically when element is loaded in html page. To achieve in this raw javascript, i can achieve it to add `load` eventListener to the element itself which will invoke the action when it is loaded. But in the stimulus, i was trying to use `data-action="load@document->MY_ACTION` to achieve the same as it said in the documentatio but somehow the action is not triggered.

**Comment by teekenl** [comment]
@robzolkos

**Comment by robzolkos** [comment]
Have you tried connect function? This gets called when the dom element connects to stimulus.

**Comment by teekenl** [comment]
@robzolkos connect might not be suitable for my case/scenario, because i have a few places that was using controller which i need them to be triggered when they are loaded in html. putting them connect does not fit to my problem here, because it will try to re-render again and again the action for the others too at the same time

**Comment by javan** [comment]
>  To achieve in this raw javascript, i can achieve it to add `load` eventListener to the element itself

There is no `load` event for non-media elements (like `<div>`s). Are you referring to the `window` load event?

>  putting them connect does not fit to my problem here, because it will try to re-render again and again the action for the others too at the same time

Stimulus doesn't do any rendering of its own so I'm not sure what you're referring to here.

> I was trying to achieve to trigger controller action automatically when element is loaded in html page

Stimulus provides two callbacks for that, `initialize()` and `connect()`, documented here: https://stimulusjs.org/reference/lifecycle-callbacks

---

The best place for *questions* like this is our community forum: https://discourse.stimulusjs.org. Feel free to continue the discussion there.
