### ISSUE TITLE
Google Maps breaks core-js Array.from on IE 11, preventing stimulus controllers to load. 

### ISSUE THREAD

**Issue by virolea** [stimulusjs/stimulus#329]
Faced an issue today where google maps API breaks `core-js`'s `Array.from` with the following message :

```
This site overrides Array.from() with an implementation that doesn't support iterables, which could cause Google Maps JavaScript API v3 to not work correctly.
```

Google Maps appears to override core-js's `Symbol.iterator` with their own polyfill thus creating the error. Anyone loading google maps on their page on IE 11 will have a JS error preventing their stimulus controllers to initialize properly without further action. 

A working solution is to add core-js's `Symbol.iterator`. 

This is not a stimulus issue per-se, but a fix would greatly improve developer experience for those who are still supporting IE11.

I'll attach a PR to this issue for your review,

**Comment by SampsonCrowley** [comment]
@virolea I think you have that backwards. That message looks like Google Maps JS is warning you someone else changed Array.from to not be the default implementation

**Comment by SampsonCrowley** [comment]
https://github.com/zloirock/core-js/issues/618

https://github.com/zloirock/core-js/issues/618#issuecomment-522618151

**Comment by javan** [comment]
Thanks! Perhaps you can follow https://github.com/auth0/auth0-spa-js/pull/592's lead (in your application):
> To fix see the 2 worksrounds in [zloirock/core-js#618](https://github.com/zloirock/core-js/issues/618)
> 
>     1. Put the maps api before the spa js SDK2.
> 
>     2. Add `import 'core-js/es6/symbol';` before importing `array-from`

Closing since this isn't a Stimulus issue.

**Comment by virolea** [comment]
hi @javan thanks for your reply,

 I had already added the workarounds in my application, I figured it was not a stimulus issue, hope this issue can help other people find a solution too. 

Have a great one
