### ISSUE TITLE
Turbolinks duplicates actions?

### ISSUE THREAD

**Issue by pascallaliberte** [stimulusjs/stimulus#33]
Here's a sample Stimulus + Turbolinks demo app:
https://pascallaliberte.github.io/stimulus-turbolinks-demo/

If an element that's watched by a Stimulus controller is on both the current and next page, Stimulus or Turbolinks seems to be connecting the actions twice (`connect`, `disconnect`, `connect`, `connect`).

<img width="1199" alt="turbolinks connect disconnect connect" src="https://user-images.githubusercontent.com/104179/34537800-c487f5d8-f097-11e7-9174-918114f919df.png">

**How to reproduce:**

1. Click between Proposals and Clients pages a few times
2. Watch the console for `dropdown#connect`, `dropdown#disconnect`
3. Click the dropdown menu (it might not open because it quickly open and then close because of multiple registered `toggle` actions
4. Watch the console for `dropdown#toggle` calls

**Comment by pascallaliberte** [comment]
(Oh, I can't prove this to you, but the theme's color choices were not at all inspired by the example demo! I chose all those (layout, colors, emojis) before even seeing that demo! Nuts huh?)

**Comment by sstephenson** [comment]
Hi there!

I don’t think this is a Stimulus issue.

Could you try moving your `<script>` tag from `<body>` to `<head>`?

```html
    <script src="/stimulus-turbolinks-demo/assets/main.js"></script>
```

When you put a `<script>` tag in the `<body>`, Turbolinks [evaluates it every time you change the page](https://github.com/turbolinks/turbolinks#working-with-script-elements). So in this case you’re actually booting up a new Stimulus app with each navigation.

**Comment by pascallaliberte** [comment]
Ah man! Of course.

All fixed up. Thanks
