### ISSUE TITLE
Updating stimulusjs.org

### ISSUE THREAD

**Issue by imajes** [stimulusjs/stimulus#333]
Hey!

@sstephenson it looks like stimulusjs.org/reference is a bit out of date -- specifically, /reference/actions -- #248 is not reflected here for example.

What can we do to trigger a rebuild? :) 

thanks!

**Comment by javan** [comment]
This should be resolved now that [v2.0.0](https://github.com/stimulusjs/stimulus/releases/tag/v2.0.0) has been released.
