### ISSUE TITLE
npm package @stimulus/polyfills out of date with repo

### ISSUE THREAD

**Issue by paulozoom** [stimulusjs/stimulus#339]
The npm package for the polyfills hasn’t been updated with https://github.com/stimulusjs/stimulus/commit/7e74768d5718b5b17aae229047f41623626c4a32

Could you please update that package?

**Comment by javan** [comment]
This should be resolved now that [v2.0.0](https://github.com/stimulusjs/stimulus/releases/tag/v2.0.0) has been released.
