### ISSUE TITLE
Testing story?

### ISSUE THREAD

**Issue by henrik** [stimulusjs/stimulus#34]
Do you have any thoughts on testing Stimulus controllers? Do you tend to unit test them in part or whole? Or rely on integrated feature tests that incorporate JS?

**Comment by javan** [comment]
We hope to provide a baked-in solution for 1.0 that may look something like https://github.com/stimulusjs/stimulus/pull/7. And, of course, you can use your application's existing test rig. We write high level feature tests using http://guides.rubyonrails.org/testing.html#system-testing.

**Comment by henrik** [comment]
@javan, thank you very much!

**Comment by sstephenson** [comment]
Quick update on testing.

We introduced the `@stimulus/test` package in version 1.0.0: https://github.com/stimulusjs/stimulus/pull/58

It’s currently undocumented but used internally by the other `@stimulus` packages. You can review their test suites here:

* [`@stimulus/core`](https://github.com/stimulusjs/stimulus/tree/master/packages/%40stimulus/core/test/cases)
* [`@stimulus/mutation-observers`](https://github.com/stimulusjs/stimulus/tree/master/packages/%40stimulus/mutation-observers/test/cases)
* [`@stimulus/webpack-helpers`](https://github.com/stimulusjs/stimulus/tree/master/packages/%40stimulus/webpack-helpers/test)

You can use this library in your applications right now. The API is stable. What we haven’t done yet is polish the experience around setting up and invoking [Karma](https://github.com/karma-runner/karma/).

**Comment by borislemke** [comment]
@sstephenson It's been a while since this was posted, I was wondering, if there was an update to the testing's suite documentation? I could not find a reference to it in your repo / handbook site.

**Comment by shime** [comment]
I've recently written an [article](https://shime.sh/testing-stimulus) that explains how to write high-level tests of Stimulus controllers. I didn't use `@stimulus/test` and I used [Jest](https://github.com/facebook/jest) instead of [Karma](https://github.com/karma-runner/karma/).

**Comment by nogtini** [comment]
This is very, very much appreciated @shime. Do you have any experience testing them through RSpec?

**Comment by nogtini** [comment]
Sure, I mean only in the context of integration tests. Seeing stimulus controllers using something like Capybara I think would help for people who are newer to Rails overall, like me. I come from a JS background, so seeing how these things are testing within the context of an entire working application is often difficult to discern.

**Comment by davidenglishmusic** [comment]
Copying the component in as a fixture instead of directly testing app code doesn't bode well for catching regressions. It seems like it would be better to only test functions which transform data, leaving others that do UI interactions to the system tests.
