### ISSUE TITLE
How rails-ujs, SJR (server-generated javascript response) fit together with Stimulus?

### ISSUE THREAD

**Issue by teohm** [stimulusjs/stimulus#37]
I assume Stimulus will work well with rails-ujs and SJR pattern, but I noticed they are not mentioned in the handbook yet.

Is it possible to briefly describe how they fit together in Basecamp today? 🙂

**Comment by jakobdamjensen** [comment]
From what I can tell it Just Works. Rendering SJR content into the DOM will automatically connect controllers defined in the content. Everything is hooked up to actions/targets. I've tested with a form rendered on the server through AJAX and manually appended to DOM.

**Comment by savroff** [comment]
it works perfectly with SJR, tested on our side too 💯

**Comment by vojtad** [comment]
Yeah, I tested it, too. It even works if you insert new content inside already existing component. All actions and targets are properly recognized.

**Comment by javan** [comment]
Stimulus works SJR and any other way you update the DOM. It's mentioned in the README:
>Stimulus continuously watches the page, kicking in as soon as magic attributes appear or disappear. It works with any update to the DOM, regardless of whether it comes from a full page load, a Turbolinks page change, or an Ajax request. Stimulus manages the whole lifecycle

**Comment by seanfcarroll** [comment]
Has anyone published some sample code on this?

**Comment by savroff** [comment]
@teohm I think you can find a nice article on Rails-ujs and Stimulus usage here:
https://medium.com/parallel-thinking/stimulus-rails-remote-forms-ca5b3e2f02ed

Also can do this with selects and other types of data, not only forms submissions and links :) 

https://guides.rubyonrails.org/working_with_javascript_in_rails.html#data-url-and-data-params
