### ISSUE TITLE
stimulus and om99

### ISSUE THREAD

**Issue by GrosSacASac** [stimulusjs/stimulus#43]
I read through all of stimulus [handbook](https://github.com/stimulusjs/stimulus/blob/master/handbook) (is there something else to read ?), and wow I am surprised it feels like we invented almost the same thing without knowing. 

[dom99 github](https://github.com/GrosSacASac/DOM99)
[dom99 docs](https://cdn.rawgit.com/GrosSacASac/DOM99/master/documentation/documentation.html)

```
stimulus - dom99

data-controller is like data-inside
data-target : data-element
data-action : data-function
```

is there something like `data-list` also ?
and `data-template` ?
 
noted differences, stimulus encourages to use a controller and put many things inside of it while dom99 approach is to let the developer structure components however he/she wants.

The docs of stimulus seems way better and more up to date and more concise.

I recommend putting `npm install stimulus` explicitly written out here https://github.com/stimulusjs/stimulus/blob/master/INSTALLING.md after the first sentence.

Thoughts ?

**Comment by javan** [comment]
> is there something like `data-list` also ? and `data-template` ?

There is not.

> I recommend putting `npm install stimulus` explicitly written out here 

We'd rather not suggest using `npm install` over `yarn install`. People already familiar with npm packages will know what to do, and [we go into more detail](https://github.com/stimulusjs/stimulus/blob/master/handbook/02_hello_stimulus.md#prerequisites) in the handbook.

---

Thanks for checking out Stimulus!

**Comment by GrosSacASac** [comment]
I wasn't sure if it was npm install `stimulusjs or stimulus`, so I had to follow a link to know it.

**Comment by javan** [comment]
I see, thanks. Clarified in 48219cffa6e20e40515bb3082b529df41b3814ff.
