### ISSUE TITLE
How create event of destroy component?

### ISSUE THREAD

**Issue by ikbc** [stimulusjs/stimulus#48]
I want remove all listeners initialed in controller code if component unmounted, how it's make?
Have any event of life circle of component except 'initialize'?

**Comment by sstephenson** [comment]
You don’t need to remove event listeners declared in `data-action` attributes—Stimulus takes care of that for you.

If you have other resources to manage, you can set them up in the `connect()` method of your controller and tear them down in the `disconnect()` method.

Hope this helps! We’ll have this documented soon.

**Comment by ikbc** [comment]
It's helps) Thanks!
