### ISSUE TITLE
[FAQ] Page-Specific Javascript 

### ISSUE THREAD

**Issue by kirantpatil** [stimulusjs/stimulus#49]
Hi,

Sorry, I didn't find any forum to post this question.

May I know, can we achieve "Page-Specific Javascript" loading as mentioned in [Organizing Javascript in Rails Application With Turbolinks](http://brandonhilkert.com/blog/organizing-javascript-in-rails-application-with-turbolinks/) article using this framework ?

Thanks.

**Comment by dixpac** [comment]
@kirantpatil when you load the page stimulus only boots up new instances of controllers that you specified on the page. It uses MutationObservers under the hood.
So it should be "Page-Specific" out of the box :)

**Comment by dhh** [comment]
What @dixpac said 👍
