### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by savroff** [stimulusjs/stimulus#54]
Hey 🖖,
Any plan to have a **public roadmap**? I'm pretty much sure a lot of people willing to contribute to the project if they will know what is needed right now.

**Comment by javan** [comment]
We don't have any major features planned so it would just be an empty document. ;) v1.0 will make some minor API changes, which we're tracking in https://github.com/stimulusjs/stimulus/milestone/1.

**Comment by savroff** [comment]
good 👍
