### ISSUE TITLE
Unminified version

### ISSUE THREAD

**Issue by rainerborene** [stimulusjs/stimulus#56]
Please provide the unminified version: `stimulus.umd.js` and `stimulus.umd.min.js`.

**Comment by javan** [comment]
For any reason in particular? Are you having trouble with the minified version?

**Comment by rainerborene** [comment]
No troubles. Just need to be able to read its code (and better leave minification work to sprockets anyway).

**Comment by dixpac** [comment]
@rainerborene  you can use `source-maps` with `webpacker` instead of sprockets at the moment, does this works?

**Comment by javan** [comment]
Most asset bundlers will use the npm package's "module", which we provide: https://github.com/stimulusjs/stimulus/blob/de381fa96e083da1c3088cab8dcb8a2dc987ba96/packages/stimulus/package.json#L12-L13

The module files are unminified and have source maps. You can browse them online if you're interested: https://unpkg.com/@stimulus/core@0.9.0/dist/module/

So, you could consider using [webpacker](https://github.com/rails/webpacker) with your Rails application. And we'll consider providing an unminified UMD version in the future.

Thanks!
