### ISSUE TITLE
NPM package for @stimulus/polyfills

### ISSUE THREAD

**Issue by rrosen** [stimulusjs/stimulus#60]
Cool project!  Would love to see a package for https://github.com/stimulusjs/stimulus/tree/master/packages/%40stimulus/polyfills on NPM to ease adding IE/Safari support.  Thanks!

**Comment by javan** [comment]
Thank you. We've outlined those polyfills and their source packages [in the installation guide](https://github.com/stimulusjs/stimulus/blob/master/INSTALLING.md#browser-support) and would rather not publish a package that just exports other packages.

**Comment by mrmartineau** [comment]
@javan the installation guide copy is not clear enough because it reads like you support IE11 without having to have polyfills. I have submitted a PR with a suggestion: https://github.com/stimulusjs/stimulus/pull/135

**Comment by mrmartineau** [comment]
@javan I also think adding @stimulus/polyfills as an npm package would be really useful

**Comment by mrmartineau** [comment]
I didn't see that the wheels were already in motion: https://github.com/stimulusjs/stimulus/pull/134

**Comment by rathboma** [comment]
+1 to adding an actual @stimulus/polyfills package
