### ISSUE TITLE
How to pass arguments through actions?

### ISSUE THREAD

**Issue by bihnkim** [stimulusjs/stimulus#64]
For the slideshow example:

If I wanted to "jump" to the second image and would like to implement a "jump" action, I need to pass in the index of the clicked image. How can this be done?

**Comment by savroff** [comment]
you get set your action like this:

In your HTML:
```
<div class="slide" data-action="click->controller#jump"></div>
```

In your JS controller:
```
jump(event) {
  const element = event.target
}
```

**Comment by savroff** [comment]
Actually check [Handbook here](https://github.com/stimulusjs/stimulus/blob/master/handbook/04_managing_state.md) with this [code example](https://github.com/stimulusjs/stimulus/blob/master/packages/%40stimulus/examples/controllers/slideshow_controller.js)

**Comment by savroff** [comment]
@bihnkim 

```html
<div data-action="jump" data-slide_index="0">Open First slide</div>
```

```javascript
jump(event) {
  const element = event.target
  this.targets.findAll('slides')[element.dataset.slide_index]
}
```

**Comment by adrienpoly** [comment]
You could also write it like this

```javascript
jump(_event, element) {
  this.targets.findAll('slides')[element.dataset.slideIndex]
  // next your logic to switch slides
}```

**Comment by javan** [comment]
Those are both reasonable options. Action methods are essentially just event handlers and there isn't a way to pass additional arguments to them.

**Comment by askehansen** [comment]
Im having some issues with the example provided by @adrianholovaty.
If you have an element inside the action element, then `_event.target` returns the nested element instead in safari.
Also `element` is just undefined.

This jsbin shows the issues: http://jsbin.com/xiyuho/edit?html,js,console,output

**Comment by adrienpoly** [comment]
@askehansen `element` as the second argument of your function was available in Stimulus 0.9 but this has been removed in 1.0. You must use now `even.target`

about safari is you look at the property of `event.target`on both browser they are the same

http://jsbin.com/nasopusali/1/edit?html,js,console,output

**Comment by javan** [comment]
> `event.target` returns the nested element

Use `event.currentTarget` to get the action element. Some related discussion here: https://discourse.stimulusjs.org/t/is-controller-scope-element-safe-to-use/109/9

**Comment by zorn-v** [comment]
> Use event.currentTarget to get the action element.

Stimulus is the crap then, no ?
Why not to introduce some other vars like "maybeThisIsWhatYouNeed" and "actuallyThisVarYouNeed" ?
Fuck standart vars.

**Comment by zorn-v** [comment]
I'm just playing with something like `data-action="click->invoices#print" data-invoice="{{ invoice.extIdString }}"` and I was surprised that sometimes it print what I want (console.log), but sometimes (several F5) "undefined" with
```
  print(e) {
    console.log(e.target.dataset.invoice)
  }
```
After change "target" to "currentTarget" all fine. Is not is the crap ?

**Comment by javan** [comment]
> Stimulus is the crap then, no ?

[No](https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget).

> ##### `Event.currentTarget`
> The *`currentTarget`* read-only property of the [`Event`](https://developer.mozilla.org/en-US/docs/Web/API/Event) interface identifies the current target for the event, as the event traverses the DOM. It always refers to the element to which the event handler has been attached, as opposed to [`Event.target`](https://developer.mozilla.org/en-US/docs/Web/API/Event/target), which identifies the element on which the event occurred and which may be its descendant.

**Comment by zorn-v** [comment]
Argument. Thanks, was not right.

**Comment by zorn-v** [comment]
What I want - defined behavior of my code.
