### ISSUE TITLE
Installation instructions outdated for v1.0.0.beta-2

### ISSUE THREAD

**Issue by dwightwatson** [stimulusjs/stimulus#69]
Just had a quick go at bumping up from `0.9.0` to `1.0.0.beta-2` and ran into an error with importing the `autoload` function.

```
ERROR in ./app/javascript/src/index.js
21:0-8 "export 'autoload' was not found in 'stimulus/webpack-helpers'
```

The [installation documentation](https://github.com/stimulusjs/stimulus/blob/master/INSTALLING.md) still indicates that this is the initialisation process, so I'm not sure if this is just outdated or an actual bug.

```
import { Application } from  'stimulus';
import { autoload } from 'stimulus/webpack-helpers';

const application = Application.start();
const controllers = require.context('./controllers', true, /\.js$/);
autoload(controllers, application);
```

**Comment by sstephenson** [comment]
Hey there! 0.9.0 is still the latest official release—the one you get when you run `yarn add stimulus`. You’ll only get the 1.0.0.beta-* versions if you explicitly install them.

We’re doing all the 1.0 work over in the [1-0 branch](https://github.com/stimulusjs/stimulus/tree/1-0). Sounds like you’re looking for the [1.0 version of the Installation Guide](https://github.com/stimulusjs/stimulus/blob/1-0/INSTALLING.md).

**Comment by dwightwatson** [comment]
My bad - didn't realise the development was happening in a different branch. I'll dig in to those now, thank you!
