### ISSUE TITLE
Nested controller folders?

### ISSUE THREAD

**Issue by jaredcwhite** [stimulusjs/stimulus#71]
I didn't see anything in the documentation, so I'm curious how you would handle nested folders and how that gets written out in the data-controller values. I like the idea of using folders to group different types of controllers together (maybe pages, forms, components, etc.)

**Comment by sstephenson** [comment]
Support for namespaced controllers is coming soon in Stimulus 1.0 (#65). For example, a controller defined in `users/list_item_controller.js` will be automatically loaded with the identifier `users--list-item`.

**Comment by jaredcwhite** [comment]
@sstephenson That sounds awesome. Thanks!

**Comment by adammiribyan** [comment]
@sstephenson @javan for some reason the nested controllers aren't being compiled in the packs-test when running a Rails system test, would that be on the Rails/Webpacker side or Stimulus?

**Comment by anchietajunior** [comment]
Hi there, is there any solution for static targets?
I have already tried:  

- data-shared--navbar-target="buttom"
- data-target="shared--navbar.buttom"

But nothing works.

**Comment by Sub-Xaero** [comment]
@anchietajunior 
Forgive me if this is patronising and I'm reading too much into a typo, but I assume your target is called `button` with an `N`, rather than `buttom` with an `M`?  
If so, can you confirm that you have tried `data-shared--navbar-target="button"`?

**Comment by anchietajunior** [comment]
> @anchietajunior
> Forgive me if this is patronising and I'm reading too much into a typo, but I assume your target is called `button` with an `N`, rather than `buttom` with an `M`?
> If so, can you confirm that you have tried `data-shared--navbar-target="button"`?

Yeap, sorry.

**Comment by awesoonmarketing** [comment]
Hey!  I understand this is an old issue, however in Rails 7 if you configure your nested folders in your import map then everything works perfectly such as:

default: 
pin_all_from 'app/javascript/controllers', under: 'controllers'

here is an extra nested folder that I have
pin_all_from 'app/javascript/controllers/ui_effects/', under: 'controllers'
