### ISSUE TITLE
Choose another name?

### ISSUE THREAD

**Issue by anity99** [stimulusjs/stimulus#81]
Hi.
The stimulus.js is really cool, but its name is not. It hard to remember and difficult to pronounce, it sounds terrible. Why don't we choose another name?

**Comment by dixpac** [comment]
I would disagree :)....The idea behind the framework is to bring back the joy when working with JS and HTML, hence it **stimulates** you to build beautiful things.

Anyway, this is a subjective topic, what really matters is what can you accomplish with the tool and how happy are you while using it.....name not so much :)

**Comment by jdbann** [comment]
I'd also say it's quite memorable when you think that your HTML is the stimulus for javascript actions.

As @dixpac says though, all subjective! Just saying I'm in support

**Comment by sstephenson** [comment]
We really like the name. Maybe it’ll grow on you!
