### ISSUE TITLE
Does Stimulus support for loops?

### ISSUE THREAD

**Issue by mydesignbuddy** [stimulusjs/stimulus#82]
Can you manage something in a loop? I didn't see examples for times when you have a list of things to manage. Example how do you manage a simple to do list? Or is this something you manage server side and with Turbolinks

**Comment by sstephenson** [comment]
Stimulus isn’t a templating language. If you can make a list of things in HTML, Stimulus can work with it. See the [Managing State](https://stimulusjs.org/handbook/managing-state) chapter of the Handbook for an example of how to handle many elements with the same target name.
