### ISSUE TITLE
Binding context

### ISSUE THREAD

**Issue by tabuna** [stimulusjs/stimulus#83]
Hello, I liked that you are heading towards a monolithic architecture.
I'm wondering whether it is planned to work with the binding context?

 Example knockoutjs:

```
<ul data-bind="template: { name: 'employeeTemplate',
                                  foreach: employees,
                                  as: 'employee' }"></ul>
```

**Comment by javan** [comment]
Not in that fashion. See the [Managing State](https://stimulusjs.org/handbook/managing-state) chapter of the Handbook for an example of working with data.
