### ISSUE TITLE
Glitch walkthrough example fails

### ISSUE THREAD

**Issue by bborn** [stimulusjs/stimulus#85]
Heads up: 
<img width="712" alt="screen shot 2018-01-31 at 10 00 40 am" src="https://user-images.githubusercontent.com/3760/35632924-a8f926ca-066d-11e8-9800-f00e69a36c6c.png">

**Comment by jeremy** [comment]
Fixed by https://github.com/stimulusjs/stimulus-starter/pull/1. Glitch was updated, too, but won't work if you already remixed using the old version. Try again by remixing https://glitch.com/edit/#!/stimulus-starter from scratch!

**Comment by davidalejandroaguilar** [comment]
The [Installation guide](https://stimulusjs.org/handbook/installing) on the Babel section mentions that you need to use either the `transform-class-properties` [plugin](https://babeljs.io/docs/plugins/transform-class-properties/) or use the `stage-2-preset` for it to transpile [class properties](https://www.andrewmunsell.com/lesson/static-and-instance-variables-in-classes/) correctly.

**Comment by javan** [comment]
Glitch's code editor fails to recognize the `static targets` class property as valid JavaScript and displays an error, which is unfortunate, but it does work. Babel compiles the code correctly.

**Comment by javan** [comment]
Moving this issue to Glitch's forum: https://support.glitch.com/t/editor-parsing-error-with-static-class-properties/2831

Thanks for the heads up!
