### ISSUE TITLE
Safari issues with the website 

### ISSUE THREAD

**Issue by tindli** [stimulusjs/stimulus#86]
First, thanks for the ideas expressed in stimulus.js - I want to use it for my next project; the description is very well-written.

Assuming that the website itself is based on turbolinks, I want to share my experience I had while using the page with the Safari browser (11.0.3) in combination with its swipe-back 2-finger gesture.

While the first problem seems to appear primarily on the desktop version, the second
problem happens on both, the mobile and desktop versions. 

- Safari freezes for up to 4 seconds:
1. Click the "Building Something Real" link in the Handbook
2. Refresh Safari at this location
3. Scroll at about 2/3 towards the end of the "Building Something Real" page
4. Click the "Introduction" link on the handbook
5. Now use the swipe back gesture of Safari to return back to the "Building Something Real" page
6. The website now freezes for up to 4 seconds...

The problem can be reproduced with every turbolinks enabled website as long as the steps above are met and the page has been scrolled far enough. I am not really sure why this happens, but I assume it is the scroll restoration of turbolinks. (looking at Safari's timeline in dev tools, it seems that the last composite of the website is delayed... until it gets responsive again)

- Serious page flicker effects:
Safari browser seems to cause a lot of flicker effects in combination with the swipe-back gesture in general, as long as the page to return to has some scrolling position. This happens on the mobile version as well.

Both effects do not appear when the back-button is used.

**Comment by danielcompton** [comment]
I can reproduce the first issue as well.

**Comment by razh** [comment]
This is an issue with Safari:

https://twitter.com/paularmstrong/status/915973363561984000

This happens with any single-page application that uses the HTML5 history API.

**Comment by razh** [comment]
Here's the bug in the WebKit Bugzilla:

https://bugs.webkit.org/show_bug.cgi?id=181269

And the fix:

https://github.com/WebKit/webkit/commit/d629a7307c48ef195e993699abcf338c7edc99be

**Comment by javan** [comment]
Happy to see this issue's been fixed upstream in webkit! Thanks for all the info.

**Comment by tindli** [comment]
@razh Thanks for your answer. The fix seems to be in webkit trunk - do you know which version of Safari will include it? The technology preview from yesterday did miss the fix...

@javan Thanks for closing the issue - lets hope for the best.

**Comment by tindli** [comment]
@razh ok thanks a lot for the information.

**Comment by razh** [comment]
This is still an issue with STP 49:

https://webkit.org/blog/8088/release-notes-for-safari-technology-preview-49/

**Comment by tindli** [comment]
@razh yeah thanks for the information. Just checked it for myself... sadly, no changes in behavior.

I really hope that the fix comes to Safari soon. What worries me, is that the revision id for the issue
(213590) is far below the issue ranges of STP 49 (227071-227873)
I have no idea how this fix ever gets into the STP if they follow revision ids upwards...
