### ISSUE TITLE
Unexpected token for static targets = ["ingredient"] in Webpack

### ISSUE THREAD

**Issue by wolves** [stimulusjs/stimulus#89]
I am receiving this after updating to 1.0 and using the new targets functionality. I have `import { Controller } from 'stimulus'` above but it seems to not be working, unless there is something I am missing

<img width="514" alt="image" src="https://user-images.githubusercontent.com/552507/35689754-31ce5054-0742-11e8-80d0-724893ffd441.png">

**Comment by razh** [comment]
Do you have the [transform-class-properties](https://babeljs.io/docs/plugins/transform-class-properties/) Babel plugin installed?

https://stimulusjs.org/handbook/installing#using-babel

**Comment by javan** [comment]
↑ (thanks @razh)

**Comment by wolves** [comment]
Ahh, yes that was it. Thank you for the fast support. Sorry I overlooked that

**Comment by aaronmoodie** [comment]
I've just updated to Webpacker 4, and I'm now seeing this error. I've followed [this upgrade guide](https://github.com/rails/webpacker/blob/master/docs/v4-upgrade.md), but not able to resolve the issue.
