### ISSUE TITLE
How to write inheritance with stimulus controller ?

### ISSUE THREAD

**Issue by thooams** [stimulusjs/stimulus#94]
```javascript
// javascript/packs/controllers/parent_controller.js
import { Controller } from "stimulus"
export class ParentController extends Controller {
  myParentFunction(){
  }
}
```
```javascript
// javascript/packes/controllers/child_controller.js
import { ParentController } from "parent_controller.js"
export default class extends ParentController {
  connect(){
    console.log("child controller loaded!")
  }    
}                               
```    
I have this error:
```
Uncaught TypeError: Super expression must either be null or a function, not object
```

**Comment by thooams** [comment]
```javascript
// javascript/packs/controllers/parent_controller.js
import { Controller } from "stimulus"
export class ParentController extends Controller {
  myParentFunction(){
  }
}
```
```javascript
// javascript/packes/controllers/child_controller.js
import  ParentController from "parent_controller.js"
export default class extends ParentController {
  connect(){
    console.log("child controller loaded!")
  }    
}                               
```    
Resolved, just remove brackets in child controller file.

**Comment by sandipsubedi** [comment]
@thooams  Do I have to do anything specific. Because I am doing exactly the same thing but getting following error:

`Error: Cannot find module "parent_controller.js"`

**Comment by tbcooney** [comment]
How can you setup webpacker to inherit from the ParentController without calling import at the top of each file?

**Comment by lukelove** [comment]
This is great!   Thank you!  I was able to extend Modal from "tailwindcss-stimulus-components" like this


```
import {Modal} from "tailwindcss-stimulus-components"

export default class extends Modal {
  connect(){
    this.element[this.identifier] = this
    this.toggleClass = 'hidden'
  }  

}
```

**Comment by jake-007** [comment]
> ```js
> // javascript/packs/controllers/parent_controller.js
> import { Controller } from "stimulus"
> export class ParentController extends Controller {
>   myParentFunction(){
>   }
> }
> ```
> 
> ```js
> // javascript/packes/controllers/child_controller.js
> import  ParentController from "parent_controller.js"
> export default class extends ParentController {
>   connect(){
>     console.log("child controller loaded!")
>   }    
> }                               
> ```
> 
> Resolved, just remove brackets in child controller file.

When parent controller is exported as
```javascript
export class ParentController extends Controller
```
it needs to be imported as
```javascript
import { ParentController } from './parent_controller'
```
Note the curly brackets. See also [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import).

**Comment by AlvaroSN** [comment]
And if I want to call just the parent controller, am I able to do it? Because I am trying it and it does not work.

**Comment by DavidPetrasek** [comment]
What if I need to extend values?

**Comment by marcoroth** [comment]
@DavidPetrasek you can just define the new values in your child controller:

```js
import { Controller } from "@hotwired/stimulus"

class ParentController extends Controller {
  static values = {
    parent: String
  }
}

// ----

import ParentController  from "./parent_controller.js"

class ChildController extends ParentController {
  static values = {
    child: String
  }

  // the child controller now has both the `parent` and `child` value
}
```

**Comment by DavidPetrasek** [comment]
@marcoroth 
This should that be a part of the documentation, because merging static properties is not a default javascript behaviour as far as I know.
