### ISSUE TITLE
Multiple events to the same action

### ISSUE THREAD

**Issue by kaspernj** [stimulusjs/stimulus#95]
I have an input text field, and I need to calculate a total when it is changed. I use the `change` and `keyup` events to do this. I couldn't find a way to bind multiple events to the same action.

If this indeed isn't possible, then I would suggest something like this:
```html
<input type="text" data-action="(change,keyup)->controllerName#calculateTotal" />
```

I couldn't find anything on multiple different events on an element either? I would suggest something like this for it:
```html
<input type="text" data-action-change="controllerName#calculateTotal" data-action-keyup="controllerName#keyUpPressed" />
```

Thank you for a great framework. This has really cleaned up my JavaScript.

**Comment by mintyPT** [comment]
Take a look: https://github.com/stimulusjs/stimulus/issues/52

**Comment by kaspernj** [comment]
@mintyPT That works. Thank you :-)
