### ISSUE TITLE
Question about documentation

### ISSUE THREAD

**Issue by benzen** [stimulusjs/stimulus#96]
In this page:
https://stimulusjs.org/handbook/managing-state
In the first version of src/controllers/slideshow_controller.js

there is a target attribute defined:

```js
 static targets = [ "slide" ]
```

But then in the `showSlide` function we use the member `slideTargets`.

Is this an incomplete rename ? 
Is there a relation a don't see explained in the rest of the document ?
Can you explain how we get from the first to the second ?

**Comment by javan** [comment]
See [What’s With That `static targets` Line?](https://stimulusjs.org/handbook/building-something-real#whats-with-that-static-targets-line) in chapter 3.

**Comment by benzen** [comment]
Well thank you very much for the VERY quick response
