### ISSUE TITLE
I'd like execute a function when a div is rendered

### ISSUE THREAD

**Issue by thooams** [stimulusjs/stimulus#98]
I'd like execute a function when a div is rendered.
```<div data-action="onload->controllername#lmyFunction"/></div>```

**Comment by thooams** [comment]
Or how to know when all controllers are loaded ?

**Comment by sstephenson** [comment]
Thanks for the question! Would you mind posting it on the [Stimulus Discourse](https://discourse.stimulusjs.org/) community forum?
